/**
 * Dashboard Widget Registry - Catalog of available widgets
 */

import type { WidgetDefinition, DashboardLayoutConfig } from './types';

// Re-export types for convenience
export type { WidgetDefinition, DashboardLayoutConfig } from './types';

export const WIDGET_REGISTRY: Record<string, WidgetDefinition> = {
  'todays-tasks': {
    id: 'todays-tasks',
    name: "Today's Tasks",
    description: 'Tasks due today with overdue alerts',
    icon: 'Sun',
    defaultSize: 'medium',
    allowedSizes: ['small', 'medium', 'large'],
    category: 'tasks',
    dataKey: 'todaysTasks',
  },
  'quick-actions': {
    id: 'quick-actions',
    name: 'Quick Actions',
    description: 'Common CRM actions at your fingertips',
    icon: 'Zap',
    defaultSize: 'small',
    allowedSizes: ['small', 'medium'],
    category: 'quick-actions',
    dataKey: 'quickActions',
  },
  'at-risk-deals': {
    id: 'at-risk-deals',
    name: 'At-Risk Deals',
    description: 'Stale deals requiring attention (7+ days)',
    icon: 'Flame',
    defaultSize: 'medium',
    allowedSizes: ['small', 'medium', 'large'],
    category: 'deals',
    dataKey: 'atRiskDeals',
  },
  'recent-activity': {
    id: 'recent-activity',
    name: 'Recent Activity',
    description: 'Latest CRM activity feed',
    icon: 'Activity',
    defaultSize: 'medium',
    allowedSizes: ['small', 'medium', 'large'],
    category: 'activity',
    dataKey: 'recentActivity',
  },
  'upcoming-tasks': {
    id: 'upcoming-tasks',
    name: 'Upcoming Tasks',
    description: 'Tasks for the next 7 days',
    icon: 'Calendar',
    defaultSize: 'medium',
    allowedSizes: ['small', 'medium', 'large'],
    category: 'tasks',
    dataKey: 'upcomingTasks',
  },
  'pipeline-summary': {
    id: 'pipeline-summary',
    name: 'Pipeline Summary',
    description: 'Deal pipeline overview by stage',
    icon: 'BarChart3',
    defaultSize: 'large',
    allowedSizes: ['medium', 'large', 'full'],
    category: 'deals',
    dataKey: 'pipelineSummary',
    comingSoon: true,
  },
  'top-deals': {
    id: 'top-deals',
    name: 'Top Deals',
    description: 'Highest value opportunities',
    icon: 'TrendingUp',
    defaultSize: 'medium',
    allowedSizes: ['small', 'medium', 'large'],
    category: 'deals',
    dataKey: 'topDeals',
    comingSoon: true,
  },
  'performance-metrics': {
    id: 'performance-metrics',
    name: 'Performance Metrics',
    description: 'Key performance indicators',
    icon: 'Target',
    defaultSize: 'large',
    allowedSizes: ['medium', 'large', 'full'],
    category: 'metrics',
    dataKey: 'performanceMetrics',
    comingSoon: true,
  },
  'calendar-events': {
    id: 'calendar-events',
    name: 'Calendar Events',
    description: 'Upcoming meetings and events',
    icon: 'CalendarDays',
    defaultSize: 'medium',
    allowedSizes: ['small', 'medium', 'large'],
    category: 'other',
    dataKey: 'calendarEvents',
  },
  'notes-memos': {
    id: 'notes-memos',
    name: 'Notes & Memos',
    description: 'Personal notes and reminders',
    icon: 'StickyNote',
    defaultSize: 'small',
    allowedSizes: ['small', 'medium'],
    category: 'other',
    dataKey: 'notesMemos',
    comingSoon: true,
  },
  'email-stats': {
    id: 'email-stats',
    name: 'Email Stats',
    description: 'Sent, opened, and replied email metrics',
    icon: 'Mail',
    defaultSize: 'medium',
    allowedSizes: ['small', 'medium', 'large'],
    category: 'email',
    dataKey: 'emailStats',
    comingSoon: true,
  },
  'lead-conversion': {
    id: 'lead-conversion',
    name: 'Lead Conversion',
    description: 'Lead to deal conversion funnel',
    icon: 'ArrowRightCircle',
    defaultSize: 'large',
    allowedSizes: ['medium', 'large', 'full'],
    category: 'metrics',
    dataKey: 'leadConversion',
    comingSoon: true,
  },
  'team-leaderboard': {
    id: 'team-leaderboard',
    name: 'Team Leaderboard',
    description: 'Top performers by deals and tasks',
    icon: 'Trophy',
    defaultSize: 'medium',
    allowedSizes: ['small', 'medium', 'large'],
    category: 'metrics',
    dataKey: 'teamLeaderboard',
    comingSoon: true,
  },
  'revenue-chart': {
    id: 'revenue-chart',
    name: 'Revenue Chart',
    description: 'Monthly and quarterly revenue trends',
    icon: 'LineChart',
    defaultSize: 'full',
    allowedSizes: ['large', 'full'],
    category: 'metrics',
    dataKey: 'revenueChart',
    comingSoon: true,
  },
  'sales-command-tiles': {
    id: 'sales-command-tiles',
    name: 'Sales Overview',
    description: 'Pipeline, leads, activity & relationships at a glance',
    icon: 'Target',
    defaultSize: 'full',
    allowedSizes: ['large', 'full'],
    category: 'metrics',
    dataKey: 'salesCommandTiles',
  },
  'module-stats': {
    id: 'module-stats',
    name: 'Module Stats',
    description: 'Record counts across your CRM modules',
    icon: 'LayoutGrid',
    defaultSize: 'full',
    allowedSizes: ['large', 'full'],
    category: 'metrics',
    dataKey: 'moduleStats',
  },
  'pipeline-funnel': {
    id: 'pipeline-funnel',
    name: 'Sales Pipeline',
    description: 'Lead to deal conversion funnel visualization',
    icon: 'BarChart3',
    defaultSize: 'full',
    allowedSizes: ['large', 'full'],
    category: 'deals',
    dataKey: 'pipelineFunnel',
  },
  'advisor-contacts': {
    id: 'advisor-contacts',
    name: 'Contacts per Advisor',
    description: 'Client breakdown by advisor with member/lead counts',
    icon: 'Users',
    defaultSize: 'large',
    allowedSizes: ['medium', 'large', 'full'],
    category: 'metrics',
    dataKey: 'advisorContacts',
  },
  'advisor-growth': {
    id: 'advisor-growth',
    name: 'Advisor Growth',
    description: 'Monthly advisor contact growth and active members',
    icon: 'TrendingUp',
    defaultSize: 'medium',
    allowedSizes: ['medium', 'large', 'full'],
    category: 'metrics',
    dataKey: 'advisorGrowth',
  },
  'top-advisors': {
    id: 'top-advisors',
    name: 'Top Advisors',
    description: 'Advisors ranked by enrollment count or revenue',
    icon: 'Trophy',
    defaultSize: 'medium',
    allowedSizes: ['small', 'medium', 'large'],
    category: 'advisors',
    dataKey: 'topAdvisors',
  },
  'lowest-churn-advisors': {
    id: 'lowest-churn-advisors',
    name: 'Lowest Churn Advisors',
    description: 'Advisors with best member retention rates',
    icon: 'Shield',
    defaultSize: 'medium',
    allowedSizes: ['small', 'medium', 'large'],
    category: 'advisors',
    dataKey: 'lowestChurnAdvisors',
  },
  'advisor-member-retention': {
    id: 'advisor-member-retention',
    name: 'Advisor Member Retention',
    description: 'Member retention rate trends over time',
    icon: 'TrendingUp',
    defaultSize: 'large',
    allowedSizes: ['medium', 'large', 'full'],
    category: 'advisors',
    dataKey: 'advisorMemberRetention',
  },
  'network-coverage-health': {
    id: 'network-coverage-health',
    name: 'Network Coverage Health',
    description: 'Provider network coverage scores and grades',
    icon: 'Shield',
    defaultSize: 'medium',
    allowedSizes: ['medium', 'large'],
    category: 'healthcare',
    dataKey: 'networkCoverageHealth',
  },
  'network-provider-stats': {
    id: 'network-provider-stats',
    name: 'Network Provider Stats',
    description: 'Provider counts by network tier',
    icon: 'Building2',
    defaultSize: 'small',
    allowedSizes: ['small', 'medium'],
    category: 'healthcare',
    dataKey: 'networkProviderStats',
  },
  'network-cost-router': {
    id: 'network-cost-router',
    name: 'Cost-Optimized Routing',
    description: 'Cheapest in-network providers for common procedures',
    icon: 'DollarSign',
    defaultSize: 'medium',
    allowedSizes: ['medium', 'large'],
    category: 'healthcare',
    dataKey: 'networkCostRouter',
  },
};

export const DEFAULT_LAYOUT: DashboardLayoutConfig = {
  widgets: [
    { id: 'widget-1', type: 'sales-command-tiles', position: 0, size: 'full' },
    { id: 'widget-2', type: 'todays-tasks', position: 1, size: 'medium' },
    { id: 'widget-3', type: 'at-risk-deals', position: 2, size: 'medium' },
    { id: 'widget-4', type: 'pipeline-funnel', position: 3, size: 'full' },
    { id: 'widget-5', type: 'recent-activity', position: 4, size: 'medium' },
    { id: 'widget-6', type: 'quick-actions', position: 5, size: 'small' },
  ],
};

export const WIDGET_CATEGORIES = [
  { id: 'tasks', label: 'Tasks', icon: 'CheckSquare' },
  { id: 'deals', label: 'Deals', icon: 'DollarSign' },
  { id: 'activity', label: 'Activity', icon: 'Activity' },
  { id: 'metrics', label: 'Metrics', icon: 'BarChart3' },
  { id: 'email', label: 'Email', icon: 'Mail' },
  { id: 'quick-actions', label: 'Actions', icon: 'Zap' },
  { id: 'advisors', label: 'Advisors', icon: 'UserCheck' },
  { id: 'healthcare', label: 'Healthcare', icon: 'Heart' },
  { id: 'other', label: 'Other', icon: 'MoreHorizontal' },
] as const;

export function getWidgetDefinition(type: string): WidgetDefinition | undefined {
  return WIDGET_REGISTRY[type];
}

export function getWidgetsByCategory(category: string): WidgetDefinition[] {
  return Object.values(WIDGET_REGISTRY).filter((w) => w.category === category);
}
