'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import { Sparkles, X, ArrowRight } from 'lucide-react';
import { Button } from '@crm-eco/ui/components/button';
import { useUiPreferences } from '@/hooks/useUiPreferences';
import { parseHabitsProfile, type HabitAiTip } from '@/lib/crm/habits/types';
import { emitHabitSignal } from '@/lib/crm/habits/beacon';

/**
 * Dashboard "For you" card — shows cached AI tips from habits.ai_tips
 * (generated by nightly cron). Zero tokens on page load.
 */
export function HabitForYouCard() {
  const { preferences, patch } = useUiPreferences();
  const habits = parseHabitsProfile(preferences.habits);
  const [localDismissed, setLocalDismissed] = useState<Set<string>>(new Set());

  const tips = useMemo(() => {
    if (!habits || habits.ai_tips_enabled === false) return [];
    return (habits.ai_tips ?? []).filter(
      (t) => !t.dismissed && !localDismissed.has(t.id),
    );
  }, [habits, localDismissed]);

  if (tips.length === 0) return null;

  const dismiss = async (tip: HabitAiTip) => {
    setLocalDismissed((prev) => new Set(prev).add(tip.id));
    emitHabitSignal('nba_dismissed', {
      module_key: tip.module_key ?? null,
      meta: { tip_id: tip.id, channel: 'ai_tip' },
    });

    if (!habits) return;
    const nextTips = (habits.ai_tips ?? []).map((t) =>
      t.id === tip.id ? { ...t, dismissed: true } : t,
    );
    await patch({
      habits: {
        ...habits,
        ai_tips: nextTips,
      },
    });
  };

  return (
    <section className="rounded-2xl border border-slate-200 dark:border-white/10 bg-white dark:bg-slate-900/50 p-4 sm:p-5 mb-4">
      <div className="flex items-start justify-between gap-3 mb-3">
        <div className="flex items-center gap-2">
          <div className="p-2 rounded-xl bg-primary/10 text-primary">
            <Sparkles className="w-4 h-4" />
          </div>
          <div>
            <h2 className="text-sm font-semibold text-slate-900 dark:text-white">
              For you
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400">
              Based on how you use the CRM
            </p>
          </div>
        </div>
      </div>
      <ul className="space-y-2">
        {tips.slice(0, 3).map((tip) => (
          <li
            key={tip.id}
            className="flex items-start gap-2 rounded-xl bg-slate-50 dark:bg-slate-800/40 px-3 py-2.5"
          >
            <p className="flex-1 text-sm text-slate-700 dark:text-slate-200 leading-snug">
              {tip.text}
            </p>
            <div className="flex items-center gap-1 shrink-0">
              {tip.module_key && (
                <Button variant="ghost" size="sm" className="h-8 px-2" asChild>
                  <Link
                    href={`/crm/modules/${tip.module_key}`}
                    onClick={() =>
                      emitHabitSignal('nba_accepted', {
                        module_key: tip.module_key,
                        meta: { tip_id: tip.id, channel: 'ai_tip' },
                      })
                    }
                  >
                    <ArrowRight className="w-3.5 h-3.5" />
                  </Link>
                </Button>
              )}
              <Button
                variant="ghost"
                size="sm"
                className="h-8 w-8 p-0 text-slate-400"
                aria-label="Dismiss tip"
                onClick={() => void dismiss(tip)}
              >
                <X className="w-3.5 h-3.5" />
              </Button>
            </div>
          </li>
        ))}
      </ul>
    </section>
  );
}
