-- Supabase ingestion schema for CRM-Eco
-- Generated: 2026-05-11T23:12:48
-- Pattern: staging schema (zoho_import) mirroring the deduped Zoho exports.
-- After loading, write your own INSERT...SELECT to project these into the
-- canonical CRM-Eco tables (leads, contacts, notes) so we don't assume your
-- production schema here.

CREATE SCHEMA IF NOT EXISTS zoho_import;

DROP TABLE IF EXISTS zoho_import.leads CASCADE;
CREATE TABLE zoho_import.leads (
  "record_id" TEXT PRIMARY KEY,
  "lead_owner_id" TEXT,
  "lead_owner" TEXT,
  "is_converted" BOOLEAN,
  "company" TEXT,
  "first_name" TEXT,
  "last_name" TEXT,
  "email" TEXT,
  "phone" TEXT,
  "mobile" TEXT,
  "lead_source" TEXT,
  "lead_status" TEXT,
  "created_by_id" TEXT,
  "created_by" TEXT,
  "modified_by_id" TEXT,
  "modified_by" TEXT,
  "created_time" TIMESTAMPTZ,
  "modified_time" TIMESTAMPTZ,
  "lead_name" TEXT,
  "street" TEXT,
  "city" TEXT,
  "state" TEXT,
  "zip_code" TEXT,
  "email_opt_out" BOOLEAN,
  "salutation" TEXT,
  "last_activity_time" TIMESTAMPTZ,
  "spouse" TEXT,
  "spouse_dob" TEXT,
  "child_1" TEXT,
  "child_1_dob" TEXT,
  "child_2" TEXT,
  "child_2_dob" TEXT,
  "child_3" TEXT,
  "child_3_dob" TEXT,
  "product_type" TEXT,
  "next_step" TEXT,
  "producer_id" TEXT,
  "producer" TEXT,
  "date_of_birth" TEXT,
  "child_5_dob" TEXT,
  "child_5" TEXT,
  "child_4_dob" TEXT,
  "child_4" TEXT,
  "coverage_option" TEXT,
  "tag" TEXT,
  "business_type" TEXT,
  "days_visited" NUMERIC,
  "average_time_spent_minutes" NUMERIC,
  "number_of_chats" NUMERIC,
  "most_recent_visit" TIMESTAMPTZ,
  "first_visit" TIMESTAMPTZ,
  "first_page_visited" TEXT,
  "referrer" TEXT,
  "visitor_score" NUMERIC,
  "data_processing_basis_details_id" TEXT,
  "data_processing_basis" TEXT,
  "data_source" TEXT,
  "middle_name" TEXT,
  "business_or_practice_name" TEXT,
  "converted_date_time" TIMESTAMPTZ,
  "lead_conversion_time" TIMESTAMPTZ,
  "unsubscribed_mode" TEXT,
  "unsubscribed_time" TIMESTAMPTZ,
  "converted_account_id" TEXT,
  "converted_account" TEXT,
  "converted_contact_id" TEXT,
  "converted_contact" TEXT,
  "converted_deal_id" TEXT,
  "converted_deal" TEXT,
  "change_log_time" TIMESTAMPTZ,
  "locked" BOOLEAN,
  "last_enriched_time" TIMESTAMPTZ,
  "enrich_status" TEXT,
  "referring_member" TEXT,
  "mobile_2" TEXT,
  "connected_to_module" TEXT,
  "connected_to_id" TEXT,
  "notes_count" NUMERIC,
  "source_files" TEXT,
  "is_also_contact" TEXT,
  "matched_contact_record_id" TEXT
);

DROP TABLE IF EXISTS zoho_import.contacts CASCADE;
CREATE TABLE zoho_import.contacts (
  "record_id" TEXT PRIMARY KEY,
  "affiliate" TEXT,
  "contact_status" TEXT,
  "contact_owner_id" TEXT,
  "contact_owner" TEXT,
  "lead_source" TEXT,
  "first_name" TEXT,
  "last_name" TEXT,
  "producer_name_id" TEXT,
  "producer_name" TEXT,
  "email" TEXT,
  "title" TEXT,
  "phone" TEXT,
  "fax" TEXT,
  "mobile" TEXT,
  "date_of_birth" TEXT,
  "created_by_id" TEXT,
  "created_by" TEXT,
  "modified_by_id" TEXT,
  "modified_by" TEXT,
  "created_time" TIMESTAMPTZ,
  "modified_time" TIMESTAMPTZ,
  "contact_name" TEXT,
  "mailing_street" TEXT,
  "mailing_city" TEXT,
  "mailing_state" TEXT,
  "mailing_zip" TEXT,
  "email_opt_out" BOOLEAN,
  "salutation" TEXT,
  "secondary_email" TEXT,
  "currency" TEXT,
  "exchange_rate" NUMERIC,
  "last_activity_time" TIMESTAMPTZ,
  "territories" TEXT,
  "spouse" TEXT,
  "spouse_dob" TEXT,
  "child_1" TEXT,
  "child_1_dob" TEXT,
  "child_2" TEXT,
  "child_2_dob" TEXT,
  "child_3" TEXT,
  "child_3_dob" TEXT,
  "primary_s_s_number" TEXT,
  "notes_history" TEXT,
  "carrier" TEXT,
  "previous_product" TEXT,
  "monthly_premium" TEXT,
  "commission_percentage" TEXT,
  "product" TEXT,
  "coverage_option" TEXT,
  "start_date" TIMESTAMPTZ,
  "referral_source" TEXT,
  "referring_member" TEXT,
  "add_on_product" TEXT,
  "declined" TEXT,
  "charge_waived" TEXT,
  "affiliate_referral" TEXT,
  "affiliate_rep_monthly" TEXT,
  "amount_received" TEXT,
  "team_leader_monthly" TEXT,
  "team_leader" TEXT,
  "primary_member_gender" TEXT,
  "mpower_life_code" TEXT,
  "welcome_call_performed_by" TEXT,
  "producer_commission" TEXT,
  "team_leader_referral" TEXT,
  "child_4" TEXT,
  "child_5_dob" TEXT,
  "child_5" TEXT,
  "child_4_dob" TEXT,
  "director" TEXT,
  "director_referral" TEXT,
  "director_monthly" TEXT,
  "4th_life_code" TEXT,
  "fulfillment_letter_mailed" TEXT,
  "fulfillment_email_sent" TEXT,
  "complete_date" TIMESTAMPTZ,
  "3rd_life_code" TEXT,
  "2nd_life_code" TEXT,
  "date_referral_paid" TIMESTAMPTZ,
  "welcome_call_status" TEXT,
  "child_4_s_s_number" TEXT,
  "mec_submitted" TEXT,
  "child_3_s_s_number" TEXT,
  "child_5_s_s_number" TEXT,
  "child_1_s_s_number" TEXT,
  "spouse_s_s_number" TEXT,
  "child_2_s_s_number" TEXT,
  "marital_status" TEXT,
  "work_phone" TEXT,
  "middle_initial" TEXT,
  "mpb_referral_fee" TEXT,
  "referral_requirement_satisfied" TEXT,
  "tag" TEXT,
  "days_visited" NUMERIC,
  "average_time_spent_minutes" NUMERIC,
  "number_of_chats" NUMERIC,
  "most_recent_visit" TIMESTAMPTZ,
  "first_visit" TIMESTAMPTZ,
  "first_page_visited" TEXT,
  "referrer" TEXT,
  "visitor_score" NUMERIC,
  "risk_assessment_paid" TEXT,
  "company_association" TEXT,
  "cancellation_date" TIMESTAMPTZ,
  "data_processing_basis_details_id" TEXT,
  "data_processing_basis" TEXT,
  "data_source" TEXT,
  "preferred_method_of_communication" TEXT,
  "vision" TEXT,
  "dental" TEXT,
  "payment_method" TEXT,
  "account_type" TEXT,
  "routing_number" TEXT,
  "account_number" TEXT,
  "iua_amount" TEXT,
  "business_or_practice_name" TEXT,
  "dpc_name" TEXT,
  "cirrus_registration_date" TIMESTAMPTZ,
  "mpb_portal_username" TEXT,
  "mpb_portal_password" TEXT,
  "select_conversion_completed" TEXT,
  "mec_decision_confirmed" TEXT,
  "unsubscribed_mode" TEXT,
  "unsubscribed_time" TIMESTAMPTZ,
  "admin123" TEXT,
  "household_annual_adj_gross" TEXT,
  "change_log_time" TIMESTAMPTZ,
  "locked" BOOLEAN,
  "last_enriched_time" TIMESTAMPTZ,
  "enrich_status" TEXT,
  "mpb_app_downloaded" TEXT,
  "birth_month" TEXT,
  "third_party_payor" TEXT,
  "atap" TEXT,
  "permission_to_discuss_plan" TEXT,
  "medical_release_form_on_file" TEXT,
  "5th_life_code" TEXT,
  "wc_outreach_date" TIMESTAMPTZ,
  "e123_member_id" TEXT,
  "child_3_address" TEXT,
  "child_3_phone_number" TEXT,
  "child_1_phone_number" TEXT,
  "child_4_address" TEXT,
  "child_1_address" TEXT,
  "child_4_phone_number" TEXT,
  "child_2_phone_number" TEXT,
  "child_5_address" TEXT,
  "child_2_address" TEXT,
  "spouse_address" TEXT,
  "child_5_phone_number" TEXT,
  "spouse_phone_number" TEXT,
  "child_1_email" TEXT,
  "child_2_email" TEXT,
  "child_3_email" TEXT,
  "child_4_email" TEXT,
  "child_5_email" TEXT,
  "spouse_email" TEXT,
  "connected_to_module" TEXT,
  "connected_to_id" TEXT,
  "tax_id" TEXT,
  "notes_count" NUMERIC,
  "source_files" TEXT
);

DROP TABLE IF EXISTS zoho_import.notes CASCADE;
CREATE TABLE zoho_import.notes (
  "note_record_id" TEXT PRIMARY KEY,
  "person_type" TEXT,
  "person_record_id" TEXT,
  "person_name" TEXT,
  "note_title" TEXT,
  "note_content" TEXT,
  "note_owner" TEXT,
  "created_by" TEXT,
  "created_time" TIMESTAMPTZ,
  "modified_time" TIMESTAMPTZ
);

DROP TABLE IF EXISTS zoho_import.unified_people CASCADE;
CREATE TABLE zoho_import.unified_people (
  "person_type" TEXT,
  "source_record_id" TEXT PRIMARY KEY,
  "first_name" TEXT,
  "last_name" TEXT,
  "full_name" TEXT,
  "email" TEXT,
  "secondary_email" TEXT,
  "phone" TEXT,
  "mobile" TEXT,
  "status" TEXT,
  "owner" TEXT,
  "notes_count" TEXT,
  "created_time" TIMESTAMPTZ,
  "modified_time" TIMESTAMPTZ,
  "linked_lead_record_id" TEXT
);

-- Helpful indexes
CREATE INDEX IF NOT EXISTS idx_zoho_leads_email      ON zoho_import.leads (LOWER(email));
CREATE INDEX IF NOT EXISTS idx_zoho_leads_phone      ON zoho_import.leads (phone);
CREATE INDEX IF NOT EXISTS idx_zoho_leads_mobile     ON zoho_import.leads (mobile);
CREATE INDEX IF NOT EXISTS idx_zoho_leads_is_contact ON zoho_import.leads (is_also_contact);

CREATE INDEX IF NOT EXISTS idx_zoho_contacts_email   ON zoho_import.contacts (LOWER(email));
CREATE INDEX IF NOT EXISTS idx_zoho_contacts_phone   ON zoho_import.contacts (phone);
CREATE INDEX IF NOT EXISTS idx_zoho_contacts_mobile  ON zoho_import.contacts (mobile);
CREATE INDEX IF NOT EXISTS idx_zoho_contacts_status  ON zoho_import.contacts (contact_status);

CREATE INDEX IF NOT EXISTS idx_zoho_notes_person     ON zoho_import.notes (person_record_id);
CREATE INDEX IF NOT EXISTS idx_zoho_notes_type       ON zoho_import.notes (person_type);
CREATE INDEX IF NOT EXISTS idx_zoho_notes_created    ON zoho_import.notes (created_time);

CREATE INDEX IF NOT EXISTS idx_zoho_unified_email    ON zoho_import.unified_people (LOWER(email));
CREATE INDEX IF NOT EXISTS idx_zoho_unified_phone    ON zoho_import.unified_people (phone);

-- Convenience view: people with their notes count + most recent note
CREATE OR REPLACE VIEW zoho_import.v_people_with_note_stats AS
SELECT
  u.person_type,
  u.source_record_id,
  u.full_name,
  u.email,
  u.phone,
  u.status,
  u.owner,
  u.notes_count,
  u.created_time,
  u.modified_time,
  (SELECT MAX(created_time) FROM zoho_import.notes n WHERE n.person_record_id = u.source_record_id) AS last_note_at,
  (SELECT note_content FROM zoho_import.notes n WHERE n.person_record_id = u.source_record_id ORDER BY created_time DESC NULLS LAST LIMIT 1) AS last_note_excerpt
FROM zoho_import.unified_people u;
