import type { GizmoHowto, GizmoPlace } from '../types';

export const ADMIN_PLACES: GizmoPlace[] = [
  { id: 'admin-dash', title: 'Dashboard', href: '/dashboard', aliases: ['home', 'overview'] },
  { id: 'admin-members', title: 'Members', href: '/members', aliases: ['member list', 'people'] },
  { id: 'admin-members-import', title: 'Import members', href: '/members/import', aliases: ['csv members'] },
  { id: 'admin-enrollments', title: 'Enrollments', href: '/enrollments', aliases: ['applications', 'apps'] },
  { id: 'admin-enroll-queue', title: 'Enrollment queue', href: '/enrollments/queue', aliases: ['review queue'] },
  { id: 'admin-enroll-abandoned', title: 'Abandoned enrollments', href: '/enrollments/abandoned', aliases: ['dropped apps'] },
  { id: 'admin-billing', title: 'Billing', href: '/billing', aliases: ['charges', 'payments'] },
  { id: 'admin-billing-tx', title: 'Billing transactions', href: '/billing/transactions', aliases: ['charges log'] },
  { id: 'admin-billing-fail', title: 'Failed payments', href: '/billing/failures', aliases: ['declined cards'] },
  { id: 'admin-invoices', title: 'Invoices', href: '/invoices', aliases: ['bills'] },
  { id: 'admin-commissions', title: 'Commissions', href: '/commissions', aliases: ['advisor pay'] },
  { id: 'admin-commission-tiers', title: 'Commission tiers', href: '/commissions/tiers', aliases: ['tier table'] },
  { id: 'admin-commission-rates', title: 'Commission rates', href: '/commissions/rates', aliases: ['rate table', 'payout rates'] },
  { id: 'admin-commission-tx', title: 'Commission transactions', href: '/commissions/transactions', aliases: ['commission log'] },
  { id: 'admin-commission-payouts', title: 'Commission payouts', href: '/commissions/payouts', aliases: ['advisor payouts'] },
  { id: 'admin-agents', title: 'Agents', href: '/agents', aliases: ['advisors', 'producers'] },
  { id: 'admin-support', title: 'Support', href: '/support', aliases: ['tickets', 'inbox support'] },
  { id: 'admin-carriers', title: 'Carriers', href: '/carriers', aliases: ['carrier list'] },
  { id: 'admin-vendors', title: 'Vendors', href: '/vendors', aliases: ['vendor list'] },
  { id: 'admin-products', title: 'Products', href: '/products', aliases: ['plans catalog'] },
  { id: 'admin-landing', title: 'Landing pages', href: '/enrollment-links', aliases: ['enrollment links'] },
  { id: 'admin-agent-links', title: 'Agent links', href: '/enrollment-links/agents', aliases: ['agent enrollment links'] },
  { id: 'admin-ops', title: 'Ops dashboard', href: '/ops', aliases: ['operations'] },
  { id: 'admin-eligibility', title: 'Eligibility', href: '/ops/eligibility', aliases: ['eligibility jobs'] },
  { id: 'admin-ops-jobs', title: 'Job history', href: '/ops/jobs', aliases: ['jobs'] },
  { id: 'admin-ops-sched', title: 'Scheduler', href: '/ops/scheduler', aliases: ['cron'] },
  { id: 'admin-comms', title: 'Communications inbox', href: '/communications/inbox', aliases: ['email'] },
  { id: 'admin-compose', title: 'Compose', href: '/communications/compose', aliases: ['send email'] },
  { id: 'admin-templates', title: 'Templates', href: '/communications/templates', aliases: ['email templates'] },
  { id: 'admin-comm-hist', title: 'Communication history', href: '/communications/history', aliases: ['sent mail'] },
  { id: 'admin-docs', title: 'Documents', href: '/documents', aliases: ['files'] },
  { id: 'admin-reports', title: 'Reports', href: '/reports', aliases: ['reporting'] },
  { id: 'admin-funnel', title: 'Enrollment funnel', href: '/analytics/funnel', aliases: ['funnel'] },
  { id: 'admin-demo', title: 'Demographics', href: '/analytics/demographics', aliases: ['member demographics'] },
  { id: 'admin-actuarial', title: 'Actuarial data', href: '/analytics/actuarial', aliases: ['actuarial'] },
  { id: 'admin-settings', title: 'Settings', href: '/settings', aliases: ['config', 'org settings'] },
  { id: 'admin-user-sec', title: 'User security', href: '/settings/security', aliases: ['mfa', 'staff security'] },
  { id: 'admin-automations', title: 'Automations', href: '/settings/automations', aliases: ['automation rules'] },
  { id: 'admin-audit', title: 'Audit logs', href: '/settings/audit-logs', aliases: ['audit'] },
  { id: 'admin-learn', title: 'Learn', href: '/learn', aliases: ['help', 'docs', 'how to'] },
  { id: 'admin-users', title: 'Users', href: '/users', aliases: ['staff', 'team access'] },
];

export const ADMIN_HOWTO: GizmoHowto[] = [
  {
    id: 'admin-howto-members',
    title: 'Find a member',
    href: '/learn',
    aliases: ['lookup member', 'member search'],
    steps: ['Ask Gizmo a name, email, or member number.', 'Or open Members and filter the table.'],
  },
  {
    id: 'admin-howto-enroll',
    title: 'Review an enrollment',
    href: '/learn',
    aliases: ['approve enrollment', 'application queue'],
    steps: ['Open Enrollments or the review queue.', 'Open the application, then approve or request more info.'],
  },
  {
    id: 'admin-howto-rates',
    title: 'Set commission rates',
    href: '/commissions/rates',
    aliases: ['commission rates', 'payout table'],
    steps: ['Open Commission rates.', 'Add a rate for the plan and period.', 'New approved enrollments pick it up on refresh.'],
  },
];
