export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          settings: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          user_id: string;
          organization_id: string;
          email: string;
          full_name: string;
          display_name: string | null;
          avatar_url: string | null;
          phone: string | null;
          time_zone: string | null;
          role: 'owner' | 'admin' | 'advisor' | 'staff';
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          organization_id: string;
          email: string;
          full_name: string;
          display_name?: string | null;
          avatar_url?: string | null;
          phone?: string | null;
          time_zone?: string | null;
          role?: 'owner' | 'admin' | 'advisor' | 'staff';
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          organization_id?: string;
          email?: string;
          full_name?: string;
          display_name?: string | null;
          avatar_url?: string | null;
          phone?: string | null;
          time_zone?: string | null;
          role?: 'owner' | 'admin' | 'advisor' | 'staff';
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      advisors: {
        Row: {
          id: string;
          organization_id: string;
          profile_id: string | null;
          parent_advisor_id: string | null;
          advisor_code: string | null;
          first_name: string;
          last_name: string;
          email: string;
          phone: string | null;
          agency_name: string | null;
          license_number: string | null;
          license_states: string[];
          npn: string | null;
          status: 'pending' | 'active' | 'paused' | 'inactive' | 'terminated';
          contract_date: string | null;
          termination_date: string | null;
          primary_channel: string | null;
          comp_level: string | null;
          commission_tier: string | null;
          // Commission-related columns
          commission_tier_id: string | null;
          commission_eligible: boolean | null;
          override_rate_pct: number | null;
          personal_production: number | null;
          team_production: number | null;
          lifetime_production: number | null;
          custom_fields: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          profile_id?: string | null;
          parent_advisor_id?: string | null;
          advisor_code?: string | null;
          first_name: string;
          last_name: string;
          email: string;
          phone?: string | null;
          agency_name?: string | null;
          license_number?: string | null;
          license_states?: string[];
          npn?: string | null;
          status?: 'pending' | 'active' | 'paused' | 'inactive' | 'terminated';
          contract_date?: string | null;
          termination_date?: string | null;
          primary_channel?: string | null;
          comp_level?: string | null;
          commission_tier?: string | null;
          // Commission-related columns
          commission_tier_id?: string | null;
          commission_eligible?: boolean | null;
          override_rate_pct?: number | null;
          personal_production?: number | null;
          team_production?: number | null;
          lifetime_production?: number | null;
          custom_fields?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          profile_id?: string | null;
          parent_advisor_id?: string | null;
          advisor_code?: string | null;
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string | null;
          agency_name?: string | null;
          license_number?: string | null;
          license_states?: string[];
          npn?: string | null;
          status?: 'pending' | 'active' | 'paused' | 'inactive' | 'terminated';
          contract_date?: string | null;
          termination_date?: string | null;
          primary_channel?: string | null;
          comp_level?: string | null;
          commission_tier?: string | null;
          // Commission-related columns
          commission_tier_id?: string | null;
          commission_eligible?: boolean | null;
          override_rate_pct?: number | null;
          personal_production?: number | null;
          team_production?: number | null;
          lifetime_production?: number | null;
          custom_fields?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      members: {
        Row: {
          id: string;
          organization_id: string;
          advisor_id: string | null;
          member_number: string | null;
          first_name: string;
          last_name: string;
          email: string;
          phone: string | null;
          date_of_birth: string | null;
          gender: string | null;
          marital_status: string | null;
          address_line1: string | null;
          address_line2: string | null;
          city: string | null;
          state: string | null;
          postal_code: string | null;
          household_id: string | null;
          household_role: string | null;
          coverage_type: string | null;
          program_type: string | null;
          status: 'prospect' | 'pending' | 'active' | 'paused' | 'terminated' | 'inactive';
          plan_name: string | null;
          plan_type: string | null;
          effective_date: string | null;
          renewal_month: number | null;
          termination_date: string | null;
          termination_reason: string | null;
          monthly_share: number | null;
          communication_preferences: Json;
          custom_fields: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          advisor_id?: string | null;
          member_number?: string | null;
          first_name: string;
          last_name: string;
          email: string;
          phone?: string | null;
          date_of_birth?: string | null;
          gender?: string | null;
          marital_status?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          household_id?: string | null;
          household_role?: string | null;
          coverage_type?: string | null;
          program_type?: string | null;
          status?: 'prospect' | 'pending' | 'active' | 'paused' | 'terminated' | 'inactive';
          plan_name?: string | null;
          plan_type?: string | null;
          effective_date?: string | null;
          renewal_month?: number | null;
          termination_date?: string | null;
          termination_reason?: string | null;
          monthly_share?: number | null;
          communication_preferences?: Json;
          custom_fields?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          advisor_id?: string | null;
          member_number?: string | null;
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string | null;
          date_of_birth?: string | null;
          gender?: string | null;
          marital_status?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          household_id?: string | null;
          household_role?: string | null;
          coverage_type?: string | null;
          program_type?: string | null;
          status?: 'prospect' | 'pending' | 'active' | 'paused' | 'terminated' | 'inactive';
          plan_name?: string | null;
          plan_type?: string | null;
          effective_date?: string | null;
          renewal_month?: number | null;
          termination_date?: string | null;
          termination_reason?: string | null;
          monthly_share?: number | null;
          communication_preferences?: Json;
          custom_fields?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      leads: {
        Row: {
          id: string;
          organization_id: string;
          advisor_id: string | null;
          source: string | null;
          campaign: string | null;
          status: 'new' | 'contacted' | 'working' | 'qualified' | 'unqualified' | 'converted' | 'lost';
          first_name: string;
          last_name: string;
          email: string;
          phone: string | null;
          state: string | null;
          household_size: number | null;
          desired_start_date: string | null;
          current_coverage: string | null;
          notes: string | null;
          custom_fields: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          advisor_id?: string | null;
          source?: string | null;
          campaign?: string | null;
          status?: 'new' | 'contacted' | 'working' | 'qualified' | 'unqualified' | 'converted' | 'lost';
          first_name: string;
          last_name: string;
          email: string;
          phone?: string | null;
          state?: string | null;
          household_size?: number | null;
          desired_start_date?: string | null;
          current_coverage?: string | null;
          notes?: string | null;
          custom_fields?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          advisor_id?: string | null;
          source?: string | null;
          campaign?: string | null;
          status?: 'new' | 'contacted' | 'working' | 'qualified' | 'unqualified' | 'converted' | 'lost';
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string | null;
          state?: string | null;
          household_size?: number | null;
          desired_start_date?: string | null;
          current_coverage?: string | null;
          notes?: string | null;
          custom_fields?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      activities: {
        Row: {
          id: string;
          organization_id: string;
          created_by_profile_id: string | null;
          profile_id: string | null; // legacy
          advisor_id: string | null;
          member_id: string | null;
          lead_id: string | null;
          entity_type: string;
          entity_id: string;
          type: string | null;
          action: string;
          subject: string | null;
          description: string | null;
          occurred_at: string;
          direction: string | null;
          via: string | null;
          metadata: Json;
          custom_fields: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          created_by_profile_id?: string | null;
          profile_id?: string | null;
          advisor_id?: string | null;
          member_id?: string | null;
          lead_id?: string | null;
          entity_type: string;
          entity_id: string;
          type?: string | null;
          action: string;
          subject?: string | null;
          description?: string | null;
          occurred_at?: string;
          direction?: string | null;
          via?: string | null;
          metadata?: Json;
          custom_fields?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          created_by_profile_id?: string | null;
          profile_id?: string | null;
          advisor_id?: string | null;
          member_id?: string | null;
          lead_id?: string | null;
          entity_type?: string;
          entity_id?: string;
          type?: string | null;
          action?: string;
          subject?: string | null;
          description?: string | null;
          occurred_at?: string;
          direction?: string | null;
          via?: string | null;
          metadata?: Json;
          custom_fields?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      tickets: {
        Row: {
          id: string;
          organization_id: string;
          created_by_profile_id: string;
          assigned_to_profile_id: string | null;
          member_id: string | null;
          advisor_id: string | null;
          agency_name: string | null;
          category: 'need' | 'enrollment' | 'billing' | 'service' | 'other';
          subject: string;
          description: string;
          status: 'open' | 'in_progress' | 'waiting' | 'resolved' | 'closed';
          priority: 'low' | 'normal' | 'high' | 'urgent';
          sla_target_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          created_by_profile_id: string;
          assigned_to_profile_id?: string | null;
          member_id?: string | null;
          advisor_id?: string | null;
          agency_name?: string | null;
          category: 'need' | 'enrollment' | 'billing' | 'service' | 'other';
          subject: string;
          description: string;
          status?: 'open' | 'in_progress' | 'waiting' | 'resolved' | 'closed';
          priority?: 'low' | 'normal' | 'high' | 'urgent';
          sla_target_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          created_by_profile_id?: string;
          assigned_to_profile_id?: string | null;
          member_id?: string | null;
          advisor_id?: string | null;
          agency_name?: string | null;
          category?: 'need' | 'enrollment' | 'billing' | 'service' | 'other';
          subject?: string;
          description?: string;
          status?: 'open' | 'in_progress' | 'waiting' | 'resolved' | 'closed';
          priority?: 'low' | 'normal' | 'high' | 'urgent';
          sla_target_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      ticket_comments: {
        Row: {
          id: string;
          ticket_id: string;
          created_by_profile_id: string;
          is_internal: boolean;
          body: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          ticket_id: string;
          created_by_profile_id: string;
          is_internal?: boolean;
          body: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          ticket_id?: string;
          created_by_profile_id?: string;
          is_internal?: boolean;
          body?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      needs: {
        Row: {
          id: string;
          organization_id: string;
          member_id: string;
          advisor_id: string | null;
          need_type: string;
          description: string;
          incident_date: string | null;
          total_amount: number;
          iua_amount: number;
          eligible_amount: number;
          reimbursed_amount: number;
          status: 'open' | 'in_review' | 'processing' | 'paid' | 'closed';
          urgency_light: 'green' | 'orange' | 'red';
          sla_target_date: string | null;
          reimbursement_method: string | null;
          reimbursement_account_last4: string | null;
          custom_fields: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          member_id: string;
          advisor_id?: string | null;
          need_type: string;
          description: string;
          incident_date?: string | null;
          total_amount?: number;
          iua_amount?: number;
          eligible_amount?: number;
          reimbursed_amount?: number;
          status?: 'open' | 'in_review' | 'processing' | 'paid' | 'closed';
          urgency_light?: 'green' | 'orange' | 'red';
          sla_target_date?: string | null;
          reimbursement_method?: string | null;
          reimbursement_account_last4?: string | null;
          custom_fields?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          member_id?: string;
          advisor_id?: string | null;
          need_type?: string;
          description?: string;
          incident_date?: string | null;
          total_amount?: number;
          iua_amount?: number;
          eligible_amount?: number;
          reimbursed_amount?: number;
          status?: 'open' | 'in_review' | 'processing' | 'paid' | 'closed';
          urgency_light?: 'green' | 'orange' | 'red';
          sla_target_date?: string | null;
          reimbursement_method?: string | null;
          reimbursement_account_last4?: string | null;
          custom_fields?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      need_events: {
        Row: {
          id: string;
          organization_id: string | null;
          need_id: string;
          created_by_profile_id: string | null;
          event_type: string;
          old_status: string | null;
          new_status: string | null;
          note: string | null;
          description: string | null;
          occurred_at: string;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id?: string | null;
          need_id: string;
          created_by_profile_id?: string | null;
          event_type: string;
          old_status?: string | null;
          new_status?: string | null;
          note?: string | null;
          description?: string | null;
          occurred_at?: string;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string | null;
          need_id?: string;
          created_by_profile_id?: string | null;
          event_type?: string;
          old_status?: string | null;
          new_status?: string | null;
          note?: string | null;
          description?: string | null;
          occurred_at?: string;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      custom_field_definitions: {
        Row: {
          id: string;
          organization_id: string;
          entity_type: 'advisor' | 'member' | 'lead' | 'need' | 'ticket';
          field_key: string | null;
          field_name: string;
          field_type: 'text' | 'number' | 'date' | 'boolean' | 'select' | 'multiselect' | 'json';
          field_label: string;
          description: string | null;
          options: Json;
          is_required: boolean;
          is_filterable: boolean;
          is_visible: boolean;
          display_order: number;
          order_index: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          entity_type: 'advisor' | 'member' | 'lead' | 'need' | 'ticket';
          field_key?: string | null;
          field_name: string;
          field_type: 'text' | 'number' | 'date' | 'boolean' | 'select' | 'multiselect' | 'json';
          field_label: string;
          description?: string | null;
          options?: Json;
          is_required?: boolean;
          is_filterable?: boolean;
          is_visible?: boolean;
          display_order?: number;
          order_index?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          entity_type?: 'advisor' | 'member' | 'lead' | 'need' | 'ticket';
          field_key?: string | null;
          field_name?: string;
          field_type?: 'text' | 'number' | 'date' | 'boolean' | 'select' | 'multiselect' | 'json';
          field_label?: string;
          description?: string | null;
          options?: Json;
          is_required?: boolean;
          is_filterable?: boolean;
          is_visible?: boolean;
          display_order?: number;
          order_index?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      // ============================================================================
      // IMPORT TABLES
      // ============================================================================
      field_mappings: {
        Row: {
          id: string;
          organization_id: string;
          entity_type: 'member' | 'advisor' | 'lead' | 'plan' | 'membership';
          source_name: string;
          name: string;
          mapping: Json;
          source_columns: Json;
          target_columns: Json;
          is_default: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          entity_type: 'member' | 'advisor' | 'lead' | 'plan' | 'membership';
          source_name: string;
          name: string;
          mapping: Json;
          source_columns?: Json;
          target_columns?: Json;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          entity_type?: 'member' | 'advisor' | 'lead' | 'plan' | 'membership';
          source_name?: string;
          name?: string;
          mapping?: Json;
          source_columns?: Json;
          target_columns?: Json;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      import_jobs: {
        Row: {
          id: string;
          organization_id: string;
          created_by_profile_id: string;
          entity_type: 'member' | 'advisor' | 'lead' | 'plan' | 'membership';
          source_name: string | null;
          file_name: string | null;
          total_rows: number;
          processed_rows: number;
          inserted_count: number;
          updated_count: number;
          skipped_count: number;
          error_count: number;
          warnings_count: number;
          status: 'pending' | 'processing' | 'completed' | 'failed';
          error_message: string | null;
          validation_errors: Json;
          is_preview: boolean;
          is_incremental: boolean;
          can_rollback: boolean;
          rollback_status: 'pending' | 'in_progress' | 'completed' | 'failed' | null;
          rollback_at: string | null;
          field_mapping_id: string | null;
          duplicate_strategy: 'skip' | 'update' | 'error';
          created_at: string;
          started_at: string | null;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          created_by_profile_id: string;
          entity_type: 'member' | 'advisor' | 'lead' | 'plan' | 'membership';
          source_name?: string | null;
          file_name?: string | null;
          total_rows?: number;
          processed_rows?: number;
          inserted_count?: number;
          updated_count?: number;
          skipped_count?: number;
          error_count?: number;
          warnings_count?: number;
          status?: 'pending' | 'processing' | 'completed' | 'failed';
          error_message?: string | null;
          validation_errors?: Json;
          is_preview?: boolean;
          is_incremental?: boolean;
          can_rollback?: boolean;
          rollback_status?: 'pending' | 'in_progress' | 'completed' | 'failed' | null;
          rollback_at?: string | null;
          field_mapping_id?: string | null;
          duplicate_strategy?: 'skip' | 'update' | 'error';
          created_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          created_by_profile_id?: string;
          entity_type?: 'member' | 'advisor' | 'lead' | 'plan' | 'membership';
          source_name?: string | null;
          file_name?: string | null;
          total_rows?: number;
          processed_rows?: number;
          inserted_count?: number;
          updated_count?: number;
          skipped_count?: number;
          error_count?: number;
          warnings_count?: number;
          status?: 'pending' | 'processing' | 'completed' | 'failed';
          error_message?: string | null;
          validation_errors?: Json;
          is_preview?: boolean;
          is_incremental?: boolean;
          can_rollback?: boolean;
          rollback_status?: 'pending' | 'in_progress' | 'completed' | 'failed' | null;
          rollback_at?: string | null;
          field_mapping_id?: string | null;
          duplicate_strategy?: 'skip' | 'update' | 'error';
          created_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
        };
        Relationships: [];
      };
      import_job_rows: {
        Row: {
          id: string;
          import_job_id: string;
          row_index: number;
          raw_data: Json;
          normalized_data: Json | null;
          entity_id: string | null;
          status: 'pending' | 'inserted' | 'updated' | 'skipped' | 'error';
          error_message: string | null;
          validation_errors: Json;
          warnings: Json;
          linked_entity_ids: Json;
          match_type: 'new' | 'exact_match' | 'fuzzy_match' | 'duplicate' | null;
          created_at: string;
          processed_at: string | null;
        };
        Insert: {
          id?: string;
          import_job_id: string;
          row_index: number;
          raw_data: Json;
          normalized_data?: Json | null;
          entity_id?: string | null;
          status?: 'pending' | 'inserted' | 'updated' | 'skipped' | 'error';
          error_message?: string | null;
          validation_errors?: Json;
          warnings?: Json;
          linked_entity_ids?: Json;
          match_type?: 'new' | 'exact_match' | 'fuzzy_match' | 'duplicate' | null;
          created_at?: string;
          processed_at?: string | null;
        };
        Update: {
          id?: string;
          import_job_id?: string;
          row_index?: number;
          raw_data?: Json;
          normalized_data?: Json | null;
          entity_id?: string | null;
          status?: 'pending' | 'inserted' | 'updated' | 'skipped' | 'error';
          error_message?: string | null;
          validation_errors?: Json;
          warnings?: Json;
          linked_entity_ids?: Json;
          match_type?: 'new' | 'exact_match' | 'fuzzy_match' | 'duplicate' | null;
          created_at?: string;
          processed_at?: string | null;
        };
        Relationships: [];
      };
      import_snapshots: {
        Row: {
          id: string;
          organization_id: string;
          import_job_id: string;
          import_job_row_id: string | null;
          entity_type: 'member' | 'advisor' | 'lead' | 'plan' | 'membership';
          entity_id: string;
          action: 'insert' | 'update';
          data_before: Json | null;
          data_after: Json;
          is_rolled_back: boolean;
          rolled_back_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          import_job_id: string;
          import_job_row_id?: string | null;
          entity_type: 'member' | 'advisor' | 'lead' | 'plan' | 'membership';
          entity_id: string;
          action: 'insert' | 'update';
          data_before?: Json | null;
          data_after: Json;
          is_rolled_back?: boolean;
          rolled_back_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          import_job_id?: string;
          import_job_row_id?: string | null;
          entity_type?: 'member' | 'advisor' | 'lead' | 'plan' | 'membership';
          entity_id?: string;
          action?: 'insert' | 'update';
          data_before?: Json | null;
          data_after?: Json;
          is_rolled_back?: boolean;
          rolled_back_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      // ============================================================================
      // ENROLLMENT ENGINE TABLES
      // ============================================================================
      plans: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          code: string;
          external_vendor_code: string | null;
          product_line: string | null;
          coverage_category: string | null;
          network_type: string | null;
          tier: string | null;
          description: string | null;
          rating_area_state: string | null;
          effective_start_date: string | null;
          effective_end_date: string | null;
          monthly_share: number | null;
          enrollment_fee: number | null;
          iua_amount: number | null;
          max_annual_share: number | null;
          is_active: boolean;
          metadata: Json;
          custom_fields: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          code: string;
          external_vendor_code?: string | null;
          product_line?: string | null;
          coverage_category?: string | null;
          network_type?: string | null;
          tier?: string | null;
          description?: string | null;
          rating_area_state?: string | null;
          effective_start_date?: string | null;
          effective_end_date?: string | null;
          monthly_share?: number | null;
          enrollment_fee?: number | null;
          iua_amount?: number | null;
          max_annual_share?: number | null;
          is_active?: boolean;
          metadata?: Json;
          custom_fields?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          name?: string;
          code?: string;
          external_vendor_code?: string | null;
          product_line?: string | null;
          coverage_category?: string | null;
          network_type?: string | null;
          tier?: string | null;
          description?: string | null;
          rating_area_state?: string | null;
          effective_start_date?: string | null;
          effective_end_date?: string | null;
          monthly_share?: number | null;
          enrollment_fee?: number | null;
          iua_amount?: number | null;
          max_annual_share?: number | null;
          is_active?: boolean;
          metadata?: Json;
          custom_fields?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      memberships: {
        Row: {
          id: string;
          organization_id: string;
          member_id: string;
          plan_id: string;
          advisor_id: string | null;
          membership_number: string | null;
          external_vendor_membership_id: string | null;
          status: 'pending' | 'active' | 'terminated' | 'paused';
          effective_date: string;
          end_date: string | null;
          billing_amount: number | null;
          billing_currency: string;
          billing_frequency: string;
          billing_status: 'ok' | 'delinquent' | 'cancelled';
          funding_type: string | null;
          primary_reason_for_joining: string | null;
          cancellation_reason: string | null;
          custom_fields: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          member_id: string;
          plan_id: string;
          advisor_id?: string | null;
          membership_number?: string | null;
          external_vendor_membership_id?: string | null;
          status?: 'pending' | 'active' | 'terminated' | 'paused';
          effective_date: string;
          end_date?: string | null;
          billing_amount?: number | null;
          billing_currency?: string;
          billing_frequency?: string;
          billing_status?: 'ok' | 'delinquent' | 'cancelled';
          funding_type?: string | null;
          primary_reason_for_joining?: string | null;
          cancellation_reason?: string | null;
          custom_fields?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          member_id?: string;
          plan_id?: string;
          advisor_id?: string | null;
          membership_number?: string | null;
          external_vendor_membership_id?: string | null;
          status?: 'pending' | 'active' | 'terminated' | 'paused';
          effective_date?: string;
          end_date?: string | null;
          billing_amount?: number | null;
          billing_currency?: string;
          billing_frequency?: string;
          billing_status?: 'ok' | 'delinquent' | 'cancelled';
          funding_type?: string | null;
          primary_reason_for_joining?: string | null;
          cancellation_reason?: string | null;
          custom_fields?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      enrollments: {
        Row: {
          id: string;
          organization_id: string;
          enrollment_number: string | null;
          primary_member_id: string;
          lead_id: string | null;
          advisor_id: string | null;
          enrollment_source: string | null;
          channel: string | null;
          status: 'draft' | 'in_progress' | 'submitted' | 'approved' | 'rejected' | 'cancelled';
          selected_plan_id: string | null;
          requested_effective_date: string | null;
          effective_date: string | null;
          household_size: number | null;
          has_mandate_warning: boolean;
          has_age65_warning: boolean;
          external_vendor_enrollment_id: string | null;
          snapshot: Json;
          custom_fields: Json;
          // Mode + Rx fields
          enrollment_mode: 'advisor_assisted' | 'member_self_serve' | 'internal_ops';
          rx_medications: Json;
          rx_pricing_result: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          enrollment_number?: string | null;
          primary_member_id: string;
          lead_id?: string | null;
          advisor_id?: string | null;
          enrollment_source?: string | null;
          channel?: string | null;
          status?: 'draft' | 'in_progress' | 'submitted' | 'approved' | 'rejected' | 'cancelled';
          selected_plan_id?: string | null;
          requested_effective_date?: string | null;
          effective_date?: string | null;
          household_size?: number | null;
          has_mandate_warning?: boolean;
          has_age65_warning?: boolean;
          external_vendor_enrollment_id?: string | null;
          snapshot?: Json;
          custom_fields?: Json;
          // Mode + Rx fields
          enrollment_mode?: 'advisor_assisted' | 'member_self_serve' | 'internal_ops';
          rx_medications?: Json;
          rx_pricing_result?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          enrollment_number?: string | null;
          primary_member_id?: string;
          lead_id?: string | null;
          advisor_id?: string | null;
          enrollment_source?: string | null;
          channel?: string | null;
          status?: 'draft' | 'in_progress' | 'submitted' | 'approved' | 'rejected' | 'cancelled';
          selected_plan_id?: string | null;
          requested_effective_date?: string | null;
          effective_date?: string | null;
          household_size?: number | null;
          has_mandate_warning?: boolean;
          has_age65_warning?: boolean;
          external_vendor_enrollment_id?: string | null;
          snapshot?: Json;
          custom_fields?: Json;
          // Mode + Rx fields
          enrollment_mode?: 'advisor_assisted' | 'member_self_serve' | 'internal_ops';
          rx_medications?: Json;
          rx_pricing_result?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      enrollment_steps: {
        Row: {
          id: string;
          organization_id: string;
          enrollment_id: string;
          step_key: string;
          is_completed: boolean;
          completed_at: string | null;
          payload: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          enrollment_id: string;
          step_key: string;
          is_completed?: boolean;
          completed_at?: string | null;
          payload?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          enrollment_id?: string;
          step_key?: string;
          is_completed?: boolean;
          completed_at?: string | null;
          payload?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      enrollment_audit_log: {
        Row: {
          id: string;
          organization_id: string;
          enrollment_id: string;
          actor_profile_id: string | null;
          event_type: string;
          old_status: string | null;
          new_status: string | null;
          message: string | null;
          data_before: Json | null;
          data_after: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          enrollment_id: string;
          actor_profile_id?: string | null;
          event_type: string;
          old_status?: string | null;
          new_status?: string | null;
          message?: string | null;
          data_before?: Json | null;
          data_after?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          enrollment_id?: string;
          actor_profile_id?: string | null;
          event_type?: string;
          old_status?: string | null;
          new_status?: string | null;
          message?: string | null;
          data_before?: Json | null;
          data_after?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      // ============================================================================
      // COMMISSION TABLES
      // ============================================================================
      commission_tiers: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          code: string;
          level: number;
          base_rate_pct: number;
          bonus_rate_pct: number | null;
          override_rate_pct: number | null;
          min_personal_production: number | null;
          min_team_production: number | null;
          min_active_members: number | null;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          code: string;
          level?: number;
          base_rate_pct: number;
          bonus_rate_pct?: number | null;
          override_rate_pct?: number | null;
          min_personal_production?: number | null;
          min_team_production?: number | null;
          min_active_members?: number | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          name?: string;
          code?: string;
          level?: number;
          base_rate_pct?: number;
          bonus_rate_pct?: number | null;
          override_rate_pct?: number | null;
          min_personal_production?: number | null;
          min_team_production?: number | null;
          min_active_members?: number | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      commission_transactions: {
        Row: {
          id: string;
          organization_id: string;
          advisor_id: string;
          enrollment_id: string | null;
          member_id: string | null;
          transaction_type: string;
          period_start: string;
          period_end: string;
          gross_amount: number;
          rate_pct: number;
          commission_amount: number;
          source_advisor_id: string | null;
          override_level: number | null;
          status: 'pending' | 'approved' | 'paid' | 'held' | 'reversed';
          paid_at: string | null;
          payout_id: string | null;
          notes: string | null;
          meta: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          advisor_id: string;
          enrollment_id?: string | null;
          member_id?: string | null;
          transaction_type: string;
          period_start: string;
          period_end: string;
          gross_amount?: number;
          rate_pct?: number;
          commission_amount?: number;
          source_advisor_id?: string | null;
          override_level?: number | null;
          status?: 'pending' | 'approved' | 'paid' | 'held' | 'reversed';
          paid_at?: string | null;
          payout_id?: string | null;
          notes?: string | null;
          meta?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          advisor_id?: string;
          enrollment_id?: string | null;
          member_id?: string | null;
          transaction_type?: string;
          period_start?: string;
          period_end?: string;
          gross_amount?: number;
          rate_pct?: number;
          commission_amount?: number;
          source_advisor_id?: string | null;
          override_level?: number | null;
          status?: 'pending' | 'approved' | 'paid' | 'held' | 'reversed';
          paid_at?: string | null;
          payout_id?: string | null;
          notes?: string | null;
          meta?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      commission_payouts: {
        Row: {
          id: string;
          organization_id: string;
          advisor_id: string;
          period_start: string;
          period_end: string;
          total_commissions: number;
          total_overrides: number | null;
          total_bonuses: number | null;
          total_chargebacks: number | null;
          net_payout: number;
          status: 'draft' | 'pending' | 'approved' | 'processing' | 'paid' | 'failed';
          approved_by: string | null;
          approved_at: string | null;
          paid_at: string | null;
          payment_method: string | null;
          payment_reference: string | null;
          notes: string | null;
          meta: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          advisor_id: string;
          period_start: string;
          period_end: string;
          total_commissions?: number;
          total_overrides?: number | null;
          total_bonuses?: number | null;
          total_chargebacks?: number | null;
          net_payout?: number;
          status?: 'draft' | 'pending' | 'approved' | 'processing' | 'paid' | 'failed';
          approved_by?: string | null;
          approved_at?: string | null;
          paid_at?: string | null;
          payment_method?: string | null;
          payment_reference?: string | null;
          notes?: string | null;
          meta?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          advisor_id?: string;
          period_start?: string;
          period_end?: string;
          total_commissions?: number;
          total_overrides?: number | null;
          total_bonuses?: number | null;
          total_chargebacks?: number | null;
          net_payout?: number;
          status?: 'draft' | 'pending' | 'approved' | 'processing' | 'paid' | 'failed';
          approved_by?: string | null;
          approved_at?: string | null;
          paid_at?: string | null;
          payment_method?: string | null;
          payment_reference?: string | null;
          notes?: string | null;
          meta?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      // ============================================================================
      // ENROLLMENT LINK TRACKING TABLES
      // ============================================================================
      enrollment_links: {
        Row: {
          id: string;
          organization_id: string;
          advisor_id: string;
          name: string;
          slug: string;
          description: string | null;
          target_url: string | null;
          product_id: string | null;
          utm_source: string | null;
          utm_medium: string | null;
          utm_campaign: string | null;
          utm_term: string | null;
          utm_content: string | null;
          is_active: boolean;
          requires_password: boolean;
          password_hash: string | null;
          max_uses: number | null;
          expires_at: string | null;
          total_visits: number;
          unique_visits: number;
          total_conversions: number;
          conversion_rate: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          advisor_id: string;
          name: string;
          slug: string;
          description?: string | null;
          target_url?: string | null;
          product_id?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_term?: string | null;
          utm_content?: string | null;
          is_active?: boolean;
          requires_password?: boolean;
          password_hash?: string | null;
          max_uses?: number | null;
          expires_at?: string | null;
          total_visits?: number;
          unique_visits?: number;
          total_conversions?: number;
          conversion_rate?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          advisor_id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          target_url?: string | null;
          product_id?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_term?: string | null;
          utm_content?: string | null;
          is_active?: boolean;
          requires_password?: boolean;
          password_hash?: string | null;
          max_uses?: number | null;
          expires_at?: string | null;
          total_visits?: number;
          unique_visits?: number;
          total_conversions?: number;
          conversion_rate?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      enrollment_link_visits: {
        Row: {
          id: string;
          organization_id: string;
          link_id: string;
          advisor_id: string | null;
          session_id: string;
          visitor_id: string | null;
          visited_at: string;
          duration_seconds: number | null;
          ip_address: string | null;
          user_agent: string | null;
          device_type: string | null;
          browser: string | null;
          browser_version: string | null;
          os: string | null;
          os_version: string | null;
          country: string | null;
          country_code: string | null;
          region: string | null;
          city: string | null;
          postal_code: string | null;
          latitude: number | null;
          longitude: number | null;
          timezone: string | null;
          referrer_url: string | null;
          referrer_domain: string | null;
          utm_source: string | null;
          utm_medium: string | null;
          utm_campaign: string | null;
          utm_term: string | null;
          utm_content: string | null;
          landing_page: string | null;
          converted: boolean;
          conversion_id: string | null;
          converted_at: string | null;
          page_views: number;
          scroll_depth_percent: number | null;
          interactions: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          link_id: string;
          advisor_id?: string | null;
          session_id: string;
          visitor_id?: string | null;
          visited_at?: string;
          duration_seconds?: number | null;
          ip_address?: string | null;
          user_agent?: string | null;
          device_type?: string | null;
          browser?: string | null;
          browser_version?: string | null;
          os?: string | null;
          os_version?: string | null;
          country?: string | null;
          country_code?: string | null;
          region?: string | null;
          city?: string | null;
          postal_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          timezone?: string | null;
          referrer_url?: string | null;
          referrer_domain?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_term?: string | null;
          utm_content?: string | null;
          landing_page?: string | null;
          converted?: boolean;
          conversion_id?: string | null;
          converted_at?: string | null;
          page_views?: number;
          scroll_depth_percent?: number | null;
          interactions?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          link_id?: string;
          advisor_id?: string | null;
          session_id?: string;
          visitor_id?: string | null;
          visited_at?: string;
          duration_seconds?: number | null;
          ip_address?: string | null;
          user_agent?: string | null;
          device_type?: string | null;
          browser?: string | null;
          browser_version?: string | null;
          os?: string | null;
          os_version?: string | null;
          country?: string | null;
          country_code?: string | null;
          region?: string | null;
          city?: string | null;
          postal_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          timezone?: string | null;
          referrer_url?: string | null;
          referrer_domain?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_term?: string | null;
          utm_content?: string | null;
          landing_page?: string | null;
          converted?: boolean;
          conversion_id?: string | null;
          converted_at?: string | null;
          page_views?: number;
          scroll_depth_percent?: number | null;
          interactions?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'enrollment_link_visits_link_id_fkey';
            columns: ['link_id'];
            referencedRelation: 'enrollment_links';
            referencedColumns: ['id'];
          }
        ];
      };
      enrollment_link_conversions: {
        Row: {
          id: string;
          organization_id: string;
          link_id: string;
          visit_id: string | null;
          advisor_id: string | null;
          enrollment_id: string | null;
          member_id: string | null;
          converted_at: string;
          time_to_convert_seconds: number | null;
          visits_before_conversion: number;
          first_touch_at: string | null;
          last_touch_at: string | null;
          attribution_model: string;
          conversion_value: number | null;
          lifetime_value: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          link_id: string;
          visit_id?: string | null;
          advisor_id?: string | null;
          enrollment_id?: string | null;
          member_id?: string | null;
          converted_at?: string;
          time_to_convert_seconds?: number | null;
          visits_before_conversion?: number;
          first_touch_at?: string | null;
          last_touch_at?: string | null;
          attribution_model?: string;
          conversion_value?: number | null;
          lifetime_value?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          link_id?: string;
          visit_id?: string | null;
          advisor_id?: string | null;
          enrollment_id?: string | null;
          member_id?: string | null;
          converted_at?: string;
          time_to_convert_seconds?: number | null;
          visits_before_conversion?: number;
          first_touch_at?: string | null;
          last_touch_at?: string | null;
          attribution_model?: string;
          conversion_value?: number | null;
          lifetime_value?: number | null;
          created_at?: string;
        };
        Relationships: [];
      };
      enrollment_link_analytics: {
        Row: {
          id: string;
          organization_id: string;
          link_id: string;
          advisor_id: string | null;
          period_date: string;
          period_type: string;
          total_visits: number;
          unique_visitors: number;
          new_visitors: number;
          returning_visitors: number;
          desktop_visits: number;
          mobile_visits: number;
          tablet_visits: number;
          avg_duration_seconds: number;
          avg_page_views: number;
          bounce_rate: number;
          total_conversions: number;
          conversion_rate: number;
          conversion_value: number;
          avg_time_to_convert_seconds: number;
          top_referrers: Json;
          top_countries: Json;
          top_devices: Json;
          calculated_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          link_id: string;
          advisor_id?: string | null;
          period_date: string;
          period_type: string;
          total_visits?: number;
          unique_visitors?: number;
          new_visitors?: number;
          returning_visitors?: number;
          desktop_visits?: number;
          mobile_visits?: number;
          tablet_visits?: number;
          avg_duration_seconds?: number;
          avg_page_views?: number;
          bounce_rate?: number;
          total_conversions?: number;
          conversion_rate?: number;
          conversion_value?: number;
          avg_time_to_convert_seconds?: number;
          top_referrers?: Json;
          top_countries?: Json;
          top_devices?: Json;
          calculated_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          link_id?: string;
          advisor_id?: string | null;
          period_date?: string;
          period_type?: string;
          total_visits?: number;
          unique_visitors?: number;
          new_visitors?: number;
          returning_visitors?: number;
          desktop_visits?: number;
          mobile_visits?: number;
          tablet_visits?: number;
          avg_duration_seconds?: number;
          avg_page_views?: number;
          bounce_rate?: number;
          total_conversions?: number;
          conversion_rate?: number;
          conversion_value?: number;
          avg_time_to_convert_seconds?: number;
          top_referrers?: Json;
          top_countries?: Json;
          top_devices?: Json;
          calculated_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      // ============================================================================
      // VENDOR MANAGEMENT TABLES
      // ============================================================================
      vendors: {
        Row: {
          id: string;
          org_id: string;
          name: string;
          code: string;
          description: string | null;
          vendor_type: 'health_plan' | 'insurance' | 'pharmacy_benefit' | 'ancillary' | 'other';
          status: 'active' | 'inactive' | 'pending' | 'suspended';
          contact_name: string | null;
          contact_email: string | null;
          contact_phone: string | null;
          website_url: string | null;
          connection_type: 'manual' | 'sftp' | 'api' | 'webhook';
          api_endpoint: string | null;
          api_key_enc: string | null;
          sftp_host: string | null;
          sftp_username: string | null;
          sftp_password_enc: string | null;
          sftp_path: string | null;
          sync_enabled: boolean;
          sync_schedule: string | null;
          last_sync_at: string | null;
          last_sync_status: string | null;
          last_sync_error: string | null;
          default_file_format: 'csv' | 'xlsx' | 'xml' | 'json';
          file_delimiter: string;
          has_header_row: boolean;
          date_format: string;
          column_mapping: Json;
          logo_url: string | null;
          settings: Json;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          name: string;
          code: string;
          description?: string | null;
          vendor_type?: 'health_plan' | 'insurance' | 'pharmacy_benefit' | 'ancillary' | 'other';
          status?: 'active' | 'inactive' | 'pending' | 'suspended';
          contact_name?: string | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          website_url?: string | null;
          connection_type?: 'manual' | 'sftp' | 'api' | 'webhook';
          api_endpoint?: string | null;
          api_key_enc?: string | null;
          sftp_host?: string | null;
          sftp_username?: string | null;
          sftp_password_enc?: string | null;
          sftp_path?: string | null;
          sync_enabled?: boolean;
          sync_schedule?: string | null;
          last_sync_at?: string | null;
          last_sync_status?: string | null;
          last_sync_error?: string | null;
          default_file_format?: 'csv' | 'xlsx' | 'xml' | 'json';
          file_delimiter?: string;
          has_header_row?: boolean;
          date_format?: string;
          column_mapping?: Json;
          logo_url?: string | null;
          settings?: Json;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          name?: string;
          code?: string;
          description?: string | null;
          vendor_type?: 'health_plan' | 'insurance' | 'pharmacy_benefit' | 'ancillary' | 'other';
          status?: 'active' | 'inactive' | 'pending' | 'suspended';
          contact_name?: string | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          website_url?: string | null;
          connection_type?: 'manual' | 'sftp' | 'api' | 'webhook';
          api_endpoint?: string | null;
          api_key_enc?: string | null;
          sftp_host?: string | null;
          sftp_username?: string | null;
          sftp_password_enc?: string | null;
          sftp_path?: string | null;
          sync_enabled?: boolean;
          sync_schedule?: string | null;
          last_sync_at?: string | null;
          last_sync_status?: string | null;
          last_sync_error?: string | null;
          default_file_format?: 'csv' | 'xlsx' | 'xml' | 'json';
          file_delimiter?: string;
          has_header_row?: boolean;
          date_format?: string;
          column_mapping?: Json;
          logo_url?: string | null;
          settings?: Json;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      vendor_files: {
        Row: {
          id: string;
          org_id: string;
          vendor_id: string;
          file_name: string;
          file_type: 'enrollment' | 'pricing' | 'roster' | 'termination' | 'change' | 'other';
          file_format: string;
          file_size_bytes: number | null;
          storage_path: string | null;
          storage_bucket: string;
          upload_source: 'manual' | 'sftp' | 'api' | 'email' | 'webhook';
          status: 'pending' | 'validating' | 'processing' | 'completed' | 'failed' | 'partially_completed';
          total_rows: number;
          processed_rows: number;
          valid_rows: number;
          error_rows: number;
          new_records: number;
          updated_records: number;
          unchanged_records: number;
          started_at: string | null;
          completed_at: string | null;
          error_message: string | null;
          error_details: Json | null;
          validation_errors: Json;
          validation_warnings: Json;
          duplicate_strategy: 'skip' | 'update' | 'error';
          detect_changes: boolean;
          uploaded_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          vendor_id: string;
          file_name: string;
          file_type: 'enrollment' | 'pricing' | 'roster' | 'termination' | 'change' | 'other';
          file_format?: string;
          file_size_bytes?: number | null;
          storage_path?: string | null;
          storage_bucket?: string;
          upload_source?: 'manual' | 'sftp' | 'api' | 'email' | 'webhook';
          status?: 'pending' | 'validating' | 'processing' | 'completed' | 'failed' | 'partially_completed';
          total_rows?: number;
          processed_rows?: number;
          valid_rows?: number;
          error_rows?: number;
          new_records?: number;
          updated_records?: number;
          unchanged_records?: number;
          started_at?: string | null;
          completed_at?: string | null;
          error_message?: string | null;
          error_details?: Json | null;
          validation_errors?: Json;
          validation_warnings?: Json;
          duplicate_strategy?: 'skip' | 'update' | 'error';
          detect_changes?: boolean;
          uploaded_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          vendor_id?: string;
          file_name?: string;
          file_type?: 'enrollment' | 'pricing' | 'roster' | 'termination' | 'change' | 'other';
          file_format?: string;
          file_size_bytes?: number | null;
          storage_path?: string | null;
          storage_bucket?: string;
          upload_source?: 'manual' | 'sftp' | 'api' | 'email' | 'webhook';
          status?: 'pending' | 'validating' | 'processing' | 'completed' | 'failed' | 'partially_completed';
          total_rows?: number;
          processed_rows?: number;
          valid_rows?: number;
          error_rows?: number;
          new_records?: number;
          updated_records?: number;
          unchanged_records?: number;
          started_at?: string | null;
          completed_at?: string | null;
          error_message?: string | null;
          error_details?: Json | null;
          validation_errors?: Json;
          validation_warnings?: Json;
          duplicate_strategy?: 'skip' | 'update' | 'error';
          detect_changes?: boolean;
          uploaded_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      vendor_file_rows: {
        Row: {
          id: string;
          org_id: string;
          file_id: string;
          row_index: number;
          raw_data: Json;
          normalized_data: Json | null;
          status: 'pending' | 'valid' | 'invalid' | 'processed' | 'skipped' | 'error';
          matched_entity_type: string | null;
          matched_entity_id: string | null;
          match_confidence: number | null;
          match_method: string | null;
          validation_errors: Json;
          validation_warnings: Json;
          action_taken: string | null;
          error_message: string | null;
          created_at: string;
          processed_at: string | null;
        };
        Insert: {
          id?: string;
          org_id: string;
          file_id: string;
          row_index: number;
          raw_data: Json;
          normalized_data?: Json | null;
          status?: 'pending' | 'valid' | 'invalid' | 'processed' | 'skipped' | 'error';
          matched_entity_type?: string | null;
          matched_entity_id?: string | null;
          match_confidence?: number | null;
          match_method?: string | null;
          validation_errors?: Json;
          validation_warnings?: Json;
          action_taken?: string | null;
          error_message?: string | null;
          created_at?: string;
          processed_at?: string | null;
        };
        Update: {
          id?: string;
          org_id?: string;
          file_id?: string;
          row_index?: number;
          raw_data?: Json;
          normalized_data?: Json | null;
          status?: 'pending' | 'valid' | 'invalid' | 'processed' | 'skipped' | 'error';
          matched_entity_type?: string | null;
          matched_entity_id?: string | null;
          match_confidence?: number | null;
          match_method?: string | null;
          validation_errors?: Json;
          validation_warnings?: Json;
          action_taken?: string | null;
          error_message?: string | null;
          created_at?: string;
          processed_at?: string | null;
        };
        Relationships: [];
      };
      vendor_changes: {
        Row: {
          id: string;
          org_id: string;
          vendor_id: string;
          file_id: string | null;
          file_row_id: string | null;
          change_type: 'new_enrollment' | 'termination' | 'demographic_update' | 'plan_change' | 'address_change' | 'status_change' | 'dependent_add' | 'dependent_remove' | 'other';
          entity_type: 'member' | 'enrollment' | 'membership' | 'dependent';
          entity_id: string | null;
          external_id: string | null;
          field_changed: string | null;
          old_value: string | null;
          new_value: string | null;
          change_data: Json;
          status: 'pending' | 'reviewed' | 'approved' | 'rejected' | 'applied' | 'ignored';
          reviewed_by: string | null;
          reviewed_at: string | null;
          review_notes: string | null;
          severity: 'low' | 'normal' | 'high' | 'critical';
          detected_at: string;
          applied_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          vendor_id: string;
          file_id?: string | null;
          file_row_id?: string | null;
          change_type: 'new_enrollment' | 'termination' | 'demographic_update' | 'plan_change' | 'address_change' | 'status_change' | 'dependent_add' | 'dependent_remove' | 'other';
          entity_type: 'member' | 'enrollment' | 'membership' | 'dependent';
          entity_id?: string | null;
          external_id?: string | null;
          field_changed?: string | null;
          old_value?: string | null;
          new_value?: string | null;
          change_data?: Json;
          status?: 'pending' | 'reviewed' | 'approved' | 'rejected' | 'applied' | 'ignored';
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          review_notes?: string | null;
          severity?: 'low' | 'normal' | 'high' | 'critical';
          detected_at?: string;
          applied_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          vendor_id?: string;
          file_id?: string | null;
          file_row_id?: string | null;
          change_type?: 'new_enrollment' | 'termination' | 'demographic_update' | 'plan_change' | 'address_change' | 'status_change' | 'dependent_add' | 'dependent_remove' | 'other';
          entity_type?: 'member' | 'enrollment' | 'membership' | 'dependent';
          entity_id?: string | null;
          external_id?: string | null;
          field_changed?: string | null;
          old_value?: string | null;
          new_value?: string | null;
          change_data?: Json;
          status?: 'pending' | 'reviewed' | 'approved' | 'rejected' | 'applied' | 'ignored';
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          review_notes?: string | null;
          severity?: 'low' | 'normal' | 'high' | 'critical';
          detected_at?: string;
          applied_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      vendor_connectors: {
        Row: {
          id: string;
          org_id: string;
          vendor_id: string;
          name: string;
          connector_type: 'enrollment_feed' | 'pricing_feed' | 'roster_sync' | 'termination_feed' | 'eligibility_check' | 'claim_submission';
          is_active: boolean;
          schedule_type: 'manual' | 'daily' | 'weekly' | 'monthly' | 'real_time';
          schedule_cron: string | null;
          last_run_at: string | null;
          next_run_at: string | null;
          config: Json;
          column_mapping: Json;
          validation_rules: Json;
          transformations: Json;
          error_threshold: number;
          error_action: 'continue' | 'pause' | 'abort';
          notification_emails: string[] | null;
          total_runs: number;
          successful_runs: number;
          failed_runs: number;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          vendor_id: string;
          name: string;
          connector_type: 'enrollment_feed' | 'pricing_feed' | 'roster_sync' | 'termination_feed' | 'eligibility_check' | 'claim_submission';
          is_active?: boolean;
          schedule_type?: 'manual' | 'daily' | 'weekly' | 'monthly' | 'real_time';
          schedule_cron?: string | null;
          last_run_at?: string | null;
          next_run_at?: string | null;
          config?: Json;
          column_mapping?: Json;
          validation_rules?: Json;
          transformations?: Json;
          error_threshold?: number;
          error_action?: 'continue' | 'pause' | 'abort';
          notification_emails?: string[] | null;
          total_runs?: number;
          successful_runs?: number;
          failed_runs?: number;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          vendor_id?: string;
          name?: string;
          connector_type?: 'enrollment_feed' | 'pricing_feed' | 'roster_sync' | 'termination_feed' | 'eligibility_check' | 'claim_submission';
          is_active?: boolean;
          schedule_type?: 'manual' | 'daily' | 'weekly' | 'monthly' | 'real_time';
          schedule_cron?: string | null;
          last_run_at?: string | null;
          next_run_at?: string | null;
          config?: Json;
          column_mapping?: Json;
          validation_rules?: Json;
          transformations?: Json;
          error_threshold?: number;
          error_action?: 'continue' | 'pause' | 'abort';
          notification_emails?: string[] | null;
          total_runs?: number;
          successful_runs?: number;
          failed_runs?: number;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      get_user_organization_id: {
        Args: Record<PropertyKey, never>;
        Returns: string;
      };
      get_user_role: {
        Args: Record<PropertyKey, never>;
        Returns: string;
      };
      get_user_advisor_id: {
        Args: Record<PropertyKey, never>;
        Returns: string;
      };
    };
    Enums: {
      [_ in never]: never;
    };
  };
}

// Helper types for easier usage
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type InsertTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert'];
export type UpdateTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update'];

// Convenience aliases
export type Organization = Tables<'organizations'>;
export type Profile = Tables<'profiles'>;
export type Advisor = Tables<'advisors'>;
export type Member = Tables<'members'>;
export type Lead = Tables<'leads'>;
export type Activity = Tables<'activities'>;
export type Ticket = Tables<'tickets'>;
export type TicketComment = Tables<'ticket_comments'>;
export type Need = Tables<'needs'>;
export type NeedEvent = Tables<'need_events'>;
export type CustomFieldDefinition = Tables<'custom_field_definitions'>;

// Import types
export type FieldMapping = Tables<'field_mappings'>;
export type ImportJob = Tables<'import_jobs'>;
export type ImportJobRow = Tables<'import_job_rows'>;
export type ImportSnapshot = Tables<'import_snapshots'>;

// Enrollment engine types
export type Plan = Tables<'plans'>;
export type Membership = Tables<'memberships'>;
export type Enrollment = Tables<'enrollments'>;
export type EnrollmentStep = Tables<'enrollment_steps'>;
export type EnrollmentAuditLog = Tables<'enrollment_audit_log'>;

// Commission types
export type CommissionTier = Tables<'commission_tiers'>;
export type CommissionTransaction = Tables<'commission_transactions'>;
export type CommissionPayout = Tables<'commission_payouts'>;

// Enrollment link tracking types
export type EnrollmentLink = Tables<'enrollment_links'>;
export type EnrollmentLinkVisit = Tables<'enrollment_link_visits'>;
export type EnrollmentLinkConversion = Tables<'enrollment_link_conversions'>;
export type EnrollmentLinkAnalytics = Tables<'enrollment_link_analytics'>;

// Vendor management types
export type Vendor = Tables<'vendors'>;
export type VendorInsert = InsertTables<'vendors'>;
export type VendorUpdate = UpdateTables<'vendors'>;
export type VendorFile = Tables<'vendor_files'>;
export type VendorFileInsert = InsertTables<'vendor_files'>;
export type VendorFileUpdate = UpdateTables<'vendor_files'>;
export type VendorFileRow = Tables<'vendor_file_rows'>;
export type VendorFileRowInsert = InsertTables<'vendor_file_rows'>;
export type VendorChange = Tables<'vendor_changes'>;
export type VendorChangeInsert = InsertTables<'vendor_changes'>;
export type VendorConnector = Tables<'vendor_connectors'>;
export type VendorConnectorInsert = InsertTables<'vendor_connectors'>;
export type VendorConnectorUpdate = UpdateTables<'vendor_connectors'>;

// Status type helpers
export type ImportJobStatus = ImportJob['status'];
export type ImportRowStatus = ImportJobRow['status'];
export type MembershipStatus = Membership['status'];
export type EnrollmentStatus = Enrollment['status'];
export type EnrollmentMode = Enrollment['enrollment_mode'];
export type BillingStatus = Membership['billing_status'];
export type CommissionTransactionStatus = CommissionTransaction['status'];
export type CommissionPayoutStatus = CommissionPayout['status'];
