export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          settings: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          user_id: string;
          organization_id: string;
          email: string;
          full_name: string;
          display_name: string | null;
          avatar_url: string | null;
          phone: string | null;
          time_zone: string | null;
          role: 'owner' | 'admin' | 'advisor' | 'staff';
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          organization_id: string;
          email: string;
          full_name: string;
          display_name?: string | null;
          avatar_url?: string | null;
          phone?: string | null;
          time_zone?: string | null;
          role?: 'owner' | 'admin' | 'advisor' | 'staff';
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          organization_id?: string;
          email?: string;
          full_name?: string;
          display_name?: string | null;
          avatar_url?: string | null;
          phone?: string | null;
          time_zone?: string | null;
          role?: 'owner' | 'admin' | 'advisor' | 'staff';
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      advisors: {
        Row: {
          id: string;
          organization_id: string;
          profile_id: string | null;
          parent_advisor_id: string | null;
          advisor_code: string | null;
          first_name: string;
          last_name: string;
          email: string;
          phone: string | null;
          agency_name: string | null;
          license_number: string | null;
          license_states: string[];
          npn: string | null;
          status: 'pending' | 'active' | 'paused' | 'inactive' | 'terminated';
          contract_date: string | null;
          termination_date: string | null;
          primary_channel: string | null;
          comp_level: string | null;
          commission_tier: string | null;
          custom_fields: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          profile_id?: string | null;
          parent_advisor_id?: string | null;
          advisor_code?: string | null;
          first_name: string;
          last_name: string;
          email: string;
          phone?: string | null;
          agency_name?: string | null;
          license_number?: string | null;
          license_states?: string[];
          npn?: string | null;
          status?: 'pending' | 'active' | 'paused' | 'inactive' | 'terminated';
          contract_date?: string | null;
          termination_date?: string | null;
          primary_channel?: string | null;
          comp_level?: string | null;
          commission_tier?: string | null;
          custom_fields?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          profile_id?: string | null;
          parent_advisor_id?: string | null;
          advisor_code?: string | null;
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string | null;
          agency_name?: string | null;
          license_number?: string | null;
          license_states?: string[];
          npn?: string | null;
          status?: 'pending' | 'active' | 'paused' | 'inactive' | 'terminated';
          contract_date?: string | null;
          termination_date?: string | null;
          primary_channel?: string | null;
          comp_level?: string | null;
          commission_tier?: string | null;
          custom_fields?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      members: {
        Row: {
          id: string;
          organization_id: string;
          advisor_id: string | null;
          member_number: string | null;
          first_name: string;
          last_name: string;
          email: string;
          phone: string | null;
          date_of_birth: string | null;
          gender: string | null;
          marital_status: string | null;
          address_line1: string | null;
          address_line2: string | null;
          city: string | null;
          state: string | null;
          postal_code: string | null;
          household_id: string | null;
          household_role: string | null;
          coverage_type: string | null;
          program_type: string | null;
          status: 'prospect' | 'pending' | 'active' | 'paused' | 'terminated' | 'inactive';
          plan_name: string | null;
          plan_type: string | null;
          effective_date: string | null;
          renewal_month: number | null;
          termination_date: string | null;
          termination_reason: string | null;
          monthly_share: number | null;
          communication_preferences: Json;
          custom_fields: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          advisor_id?: string | null;
          member_number?: string | null;
          first_name: string;
          last_name: string;
          email: string;
          phone?: string | null;
          date_of_birth?: string | null;
          gender?: string | null;
          marital_status?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          household_id?: string | null;
          household_role?: string | null;
          coverage_type?: string | null;
          program_type?: string | null;
          status?: 'prospect' | 'pending' | 'active' | 'paused' | 'terminated' | 'inactive';
          plan_name?: string | null;
          plan_type?: string | null;
          effective_date?: string | null;
          renewal_month?: number | null;
          termination_date?: string | null;
          termination_reason?: string | null;
          monthly_share?: number | null;
          communication_preferences?: Json;
          custom_fields?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          advisor_id?: string | null;
          member_number?: string | null;
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string | null;
          date_of_birth?: string | null;
          gender?: string | null;
          marital_status?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          household_id?: string | null;
          household_role?: string | null;
          coverage_type?: string | null;
          program_type?: string | null;
          status?: 'prospect' | 'pending' | 'active' | 'paused' | 'terminated' | 'inactive';
          plan_name?: string | null;
          plan_type?: string | null;
          effective_date?: string | null;
          renewal_month?: number | null;
          termination_date?: string | null;
          termination_reason?: string | null;
          monthly_share?: number | null;
          communication_preferences?: Json;
          custom_fields?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      leads: {
        Row: {
          id: string;
          organization_id: string;
          advisor_id: string | null;
          source: string | null;
          campaign: string | null;
          status: 'new' | 'contacted' | 'working' | 'qualified' | 'unqualified' | 'converted' | 'lost';
          first_name: string;
          last_name: string;
          email: string;
          phone: string | null;
          state: string | null;
          household_size: number | null;
          desired_start_date: string | null;
          current_coverage: string | null;
          notes: string | null;
          custom_fields: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          advisor_id?: string | null;
          source?: string | null;
          campaign?: string | null;
          status?: 'new' | 'contacted' | 'working' | 'qualified' | 'unqualified' | 'converted' | 'lost';
          first_name: string;
          last_name: string;
          email: string;
          phone?: string | null;
          state?: string | null;
          household_size?: number | null;
          desired_start_date?: string | null;
          current_coverage?: string | null;
          notes?: string | null;
          custom_fields?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          advisor_id?: string | null;
          source?: string | null;
          campaign?: string | null;
          status?: 'new' | 'contacted' | 'working' | 'qualified' | 'unqualified' | 'converted' | 'lost';
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string | null;
          state?: string | null;
          household_size?: number | null;
          desired_start_date?: string | null;
          current_coverage?: string | null;
          notes?: string | null;
          custom_fields?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      activities: {
        Row: {
          id: string;
          organization_id: string;
          created_by_profile_id: string | null;
          profile_id: string | null; // legacy
          advisor_id: string | null;
          member_id: string | null;
          lead_id: string | null;
          entity_type: string;
          entity_id: string;
          type: string | null;
          action: string;
          subject: string | null;
          description: string | null;
          occurred_at: string;
          direction: string | null;
          via: string | null;
          metadata: Json;
          custom_fields: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          created_by_profile_id?: string | null;
          profile_id?: string | null;
          advisor_id?: string | null;
          member_id?: string | null;
          lead_id?: string | null;
          entity_type: string;
          entity_id: string;
          type?: string | null;
          action: string;
          subject?: string | null;
          description?: string | null;
          occurred_at?: string;
          direction?: string | null;
          via?: string | null;
          metadata?: Json;
          custom_fields?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          created_by_profile_id?: string | null;
          profile_id?: string | null;
          advisor_id?: string | null;
          member_id?: string | null;
          lead_id?: string | null;
          entity_type?: string;
          entity_id?: string;
          type?: string | null;
          action?: string;
          subject?: string | null;
          description?: string | null;
          occurred_at?: string;
          direction?: string | null;
          via?: string | null;
          metadata?: Json;
          custom_fields?: Json;
          created_at?: string;
        };
      };
      tickets: {
        Row: {
          id: string;
          organization_id: string;
          created_by_profile_id: string;
          assigned_to_profile_id: string | null;
          member_id: string | null;
          advisor_id: string | null;
          agency_name: string | null;
          category: 'need' | 'enrollment' | 'billing' | 'service' | 'other';
          subject: string;
          description: string;
          status: 'open' | 'in_progress' | 'waiting' | 'resolved' | 'closed';
          priority: 'low' | 'normal' | 'high' | 'urgent';
          sla_target_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          created_by_profile_id: string;
          assigned_to_profile_id?: string | null;
          member_id?: string | null;
          advisor_id?: string | null;
          agency_name?: string | null;
          category: 'need' | 'enrollment' | 'billing' | 'service' | 'other';
          subject: string;
          description: string;
          status?: 'open' | 'in_progress' | 'waiting' | 'resolved' | 'closed';
          priority?: 'low' | 'normal' | 'high' | 'urgent';
          sla_target_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          created_by_profile_id?: string;
          assigned_to_profile_id?: string | null;
          member_id?: string | null;
          advisor_id?: string | null;
          agency_name?: string | null;
          category?: 'need' | 'enrollment' | 'billing' | 'service' | 'other';
          subject?: string;
          description?: string;
          status?: 'open' | 'in_progress' | 'waiting' | 'resolved' | 'closed';
          priority?: 'low' | 'normal' | 'high' | 'urgent';
          sla_target_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      ticket_comments: {
        Row: {
          id: string;
          ticket_id: string;
          created_by_profile_id: string;
          is_internal: boolean;
          body: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          ticket_id: string;
          created_by_profile_id: string;
          is_internal?: boolean;
          body: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          ticket_id?: string;
          created_by_profile_id?: string;
          is_internal?: boolean;
          body?: string;
          created_at?: string;
        };
      };
      needs: {
        Row: {
          id: string;
          organization_id: string;
          member_id: string;
          advisor_id: string | null;
          need_type: string;
          description: string;
          incident_date: string | null;
          total_amount: number;
          iua_amount: number;
          eligible_amount: number;
          reimbursed_amount: number;
          status: 'open' | 'in_review' | 'processing' | 'paid' | 'closed';
          urgency_light: 'green' | 'orange' | 'red';
          sla_target_date: string | null;
          reimbursement_method: string | null;
          reimbursement_account_last4: string | null;
          custom_fields: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          member_id: string;
          advisor_id?: string | null;
          need_type: string;
          description: string;
          incident_date?: string | null;
          total_amount?: number;
          iua_amount?: number;
          eligible_amount?: number;
          reimbursed_amount?: number;
          status?: 'open' | 'in_review' | 'processing' | 'paid' | 'closed';
          urgency_light?: 'green' | 'orange' | 'red';
          sla_target_date?: string | null;
          reimbursement_method?: string | null;
          reimbursement_account_last4?: string | null;
          custom_fields?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          member_id?: string;
          advisor_id?: string | null;
          need_type?: string;
          description?: string;
          incident_date?: string | null;
          total_amount?: number;
          iua_amount?: number;
          eligible_amount?: number;
          reimbursed_amount?: number;
          status?: 'open' | 'in_review' | 'processing' | 'paid' | 'closed';
          urgency_light?: 'green' | 'orange' | 'red';
          sla_target_date?: string | null;
          reimbursement_method?: string | null;
          reimbursement_account_last4?: string | null;
          custom_fields?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      need_events: {
        Row: {
          id: string;
          organization_id: string | null;
          need_id: string;
          created_by_profile_id: string | null;
          event_type: string;
          old_status: string | null;
          new_status: string | null;
          note: string | null;
          description: string | null;
          occurred_at: string;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id?: string | null;
          need_id: string;
          created_by_profile_id?: string | null;
          event_type: string;
          old_status?: string | null;
          new_status?: string | null;
          note?: string | null;
          description?: string | null;
          occurred_at?: string;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string | null;
          need_id?: string;
          created_by_profile_id?: string | null;
          event_type?: string;
          old_status?: string | null;
          new_status?: string | null;
          note?: string | null;
          description?: string | null;
          occurred_at?: string;
          metadata?: Json;
          created_at?: string;
        };
      };
      custom_field_definitions: {
        Row: {
          id: string;
          organization_id: string;
          entity_type: 'advisor' | 'member' | 'lead' | 'need' | 'ticket';
          field_key: string | null;
          field_name: string;
          field_type: 'text' | 'number' | 'date' | 'boolean' | 'select' | 'multiselect' | 'json';
          field_label: string;
          description: string | null;
          options: Json;
          is_required: boolean;
          is_filterable: boolean;
          is_visible: boolean;
          display_order: number;
          order_index: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          entity_type: 'advisor' | 'member' | 'lead' | 'need' | 'ticket';
          field_key?: string | null;
          field_name: string;
          field_type: 'text' | 'number' | 'date' | 'boolean' | 'select' | 'multiselect' | 'json';
          field_label: string;
          description?: string | null;
          options?: Json;
          is_required?: boolean;
          is_filterable?: boolean;
          is_visible?: boolean;
          display_order?: number;
          order_index?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          entity_type?: 'advisor' | 'member' | 'lead' | 'need' | 'ticket';
          field_key?: string | null;
          field_name?: string;
          field_type?: 'text' | 'number' | 'date' | 'boolean' | 'select' | 'multiselect' | 'json';
          field_label?: string;
          description?: string | null;
          options?: Json;
          is_required?: boolean;
          is_filterable?: boolean;
          is_visible?: boolean;
          display_order?: number;
          order_index?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      get_user_organization_id: {
        Args: Record<PropertyKey, never>;
        Returns: string;
      };
      get_user_role: {
        Args: Record<PropertyKey, never>;
        Returns: string;
      };
      get_user_advisor_id: {
        Args: Record<PropertyKey, never>;
        Returns: string;
      };
    };
    Enums: {
      [_ in never]: never;
    };
  };
}

// Helper types for easier usage
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type InsertTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert'];
export type UpdateTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update'];

// Convenience aliases
export type Organization = Tables<'organizations'>;
export type Profile = Tables<'profiles'>;
export type Advisor = Tables<'advisors'>;
export type Member = Tables<'members'>;
export type Lead = Tables<'leads'>;
export type Activity = Tables<'activities'>;
export type Ticket = Tables<'tickets'>;
export type TicketComment = Tables<'ticket_comments'>;
export type Need = Tables<'needs'>;
export type NeedEvent = Tables<'need_events'>;
export type CustomFieldDefinition = Tables<'custom_field_definitions'>;
