export { RecordTable } from './RecordTable';
export { DynamicRecordForm } from './DynamicRecordForm';
export { FieldRenderer, renderCellValue, getDisplayValue } from './FieldRenderer';
export { CommunicationsTab } from './CommunicationsTab';
export { StageBar } from './StageBar';
export { TransitionModal } from './TransitionModal';
export { ApprovalPanel } from './ApprovalPanel';
export { RecordDetailShellV2 } from './RecordDetailShellV2';
export { RecordTimeline } from './RecordTimeline';
export { AttachmentsPanel } from './AttachmentsPanel';
export { AttachmentsSectionClient } from './AttachmentsSectionClient';
export { RelatedRecordsPanel, type LinkCandidate } from './RelatedRecordsPanel';
export { ActivityForm } from './ActivityForm';
