-- Phase 8a: Supabase linter — unindexed_foreign_keys (covering indexes)
-- Project: sffisarikcreyyjzdjvb (PIF-ECO-V2 production)
-- Linter: unindexed_foreign_keys — 199 FK constraints, 198 unique column sets
-- Risk: LOW — additive indexes only, no data mutation, fully reversible
-- Rollback: DROP INDEX IF EXISTS for each idx_*_fkey created below

BEGIN;

SET lock_timeout = '5s';

CREATE INDEX IF NOT EXISTS idx_admin_notifications_organization_id_fkey ON public.admin_notifications (organization_id); -- admin_notifications_organization_id_fkey
CREATE INDEX IF NOT EXISTS idx_advisor_product_access_granted_by_fkey ON public.advisor_product_access (granted_by); -- advisor_product_access_granted_by_fkey
CREATE INDEX IF NOT EXISTS idx_advisor_score_config_created_by_fkey ON public.advisor_score_config (created_by); -- advisor_score_config_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_advisor_score_config_updated_by_fkey ON public.advisor_score_config (updated_by); -- advisor_score_config_updated_by_fkey
CREATE INDEX IF NOT EXISTS idx_advisors_agent_level_id_fkey ON public.advisors (agent_level_id); -- advisors_agent_level_id_fkey
CREATE INDEX IF NOT EXISTS idx_age_up_out_results_action_by_fkey ON public.age_up_out_results (action_by); -- age_up_out_results_action_by_fkey
CREATE INDEX IF NOT EXISTS idx_age_up_out_results_membership_id_fkey ON public.age_up_out_results (membership_id); -- age_up_out_results_membership_id_fkey
CREATE INDEX IF NOT EXISTS idx_agreement_signatures_legal_document_id_fkey ON public.agreement_signatures (legal_document_id); -- agreement_signatures_legal_document_id_fkey
CREATE INDEX IF NOT EXISTS idx_approval_blocks_approval_id_fkey ON public.approval_blocks (approval_id); -- approval_blocks_approval_id_fkey
CREATE INDEX IF NOT EXISTS idx_approval_blocks_resolved_by_fkey ON public.approval_blocks (resolved_by); -- approval_blocks_resolved_by_fkey
CREATE INDEX IF NOT EXISTS idx_approval_blocks_rule_id_fkey ON public.approval_blocks (rule_id); -- approval_blocks_rule_id_fkey
CREATE INDEX IF NOT EXISTS idx_automation_rule_runs_event_id_fkey ON public.automation_rule_runs (event_id); -- automation_rule_runs_event_id_fkey
CREATE INDEX IF NOT EXISTS idx_automation_rules_created_by_fkey ON public.automation_rules (created_by); -- automation_rules_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_automation_rules_updated_by_fkey ON public.automation_rules (updated_by); -- automation_rules_updated_by_fkey
CREATE INDEX IF NOT EXISTS idx_billing_audit_log_user_id_fkey ON public.billing_audit_log (user_id); -- billing_audit_log_user_id_fkey
CREATE INDEX IF NOT EXISTS idx_billing_failures_enrollment_id_fkey ON public.billing_failures (enrollment_id); -- fk_billing_failures_enrollment
CREATE INDEX IF NOT EXISTS idx_billing_schedules_last_failure_id_fkey ON public.billing_schedules (last_failure_id); -- billing_schedules_last_failure_id_fkey
CREATE INDEX IF NOT EXISTS idx_calendar_events_linked_task_id_fkey ON public.calendar_events (linked_task_id); -- calendar_events_linked_task_id_fkey
CREATE INDEX IF NOT EXISTS idx_commission_adjustments_approved_by_fkey ON public.commission_adjustments (approved_by); -- commission_adjustments_approved_by_fkey
CREATE INDEX IF NOT EXISTS idx_commission_adjustments_commission_id_fkey ON public.commission_adjustments (commission_id); -- commission_adjustments_commission_id_fkey
CREATE INDEX IF NOT EXISTS idx_commission_adjustments_created_by_fkey ON public.commission_adjustments (created_by); -- commission_adjustments_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_commission_adjustments_enrollment_id_fkey ON public.commission_adjustments (enrollment_id); -- commission_adjustments_enrollment_id_fkey
CREATE INDEX IF NOT EXISTS idx_commission_copy_history_created_by_fkey ON public.commission_copy_history (created_by); -- commission_copy_history_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_commission_ledger_payout_id_fkey ON public.commission_ledger (payout_id); -- commission_ledger_payout_id_fkey
CREATE INDEX IF NOT EXISTS idx_commission_payment_batches_approved_by_fkey ON public.commission_payment_batches (approved_by); -- commission_payment_batches_approved_by_fkey
CREATE INDEX IF NOT EXISTS idx_commission_payment_batches_processed_by_fkey ON public.commission_payment_batches (processed_by); -- commission_payment_batches_processed_by_fkey
CREATE INDEX IF NOT EXISTS idx_commissions_bonus_type_id_fkey ON public.commissions (bonus_type_id); -- commissions_bonus_type_id_fkey
CREATE INDEX IF NOT EXISTS idx_crm_activation_outbox_org_id_fkey ON public.crm_activation_outbox (org_id); -- crm_activation_outbox_org_id_fkey
CREATE INDEX IF NOT EXISTS idx_crm_activities_completed_by_fkey ON public.crm_activities (completed_by); -- crm_activities_completed_by_fkey
CREATE INDEX IF NOT EXISTS idx_crm_activities_created_by_fkey ON public.crm_activities (created_by); -- crm_activities_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_crm_activities_module_id_fkey ON public.crm_activities (module_id); -- crm_activities_module_id_fkey
CREATE INDEX IF NOT EXISTS idx_crm_advisor_carriers_user_id_fkey ON public.crm_advisor_carriers (user_id); -- crm_advisor_carriers_user_id_fkey
CREATE INDEX IF NOT EXISTS idx_crm_age_65_cancellation_outbox_org_id_fkey ON public.crm_age_65_cancellation_outbox (org_id); -- crm_age_65_cancellation_outbox_org_id_fkey
CREATE INDEX IF NOT EXISTS idx_crm_api_keys_created_by_fkey ON public.crm_api_keys (created_by); -- crm_api_keys_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_crm_api_keys_revoked_by_fkey ON public.crm_api_keys (revoked_by); -- crm_api_keys_revoked_by_fkey
CREATE INDEX IF NOT EXISTS idx_crm_duplicate_dismissals_dismissed_by_fkey ON public.crm_duplicate_dismissals (dismissed_by); -- crm_duplicate_dismissals_dismissed_by_fkey
CREATE INDEX IF NOT EXISTS idx_crm_extension_installs_installed_by_fkey ON public.crm_extension_installs (installed_by); -- crm_extension_installs_installed_by_fkey
CREATE INDEX IF NOT EXISTS idx_crm_extension_reviews_organization_id_fkey ON public.crm_extension_reviews (organization_id); -- crm_extension_reviews_organization_id_fkey
CREATE INDEX IF NOT EXISTS idx_crm_extension_reviews_reviewer_id_fkey ON public.crm_extension_reviews (reviewer_id); -- crm_extension_reviews_reviewer_id_fkey
CREATE INDEX IF NOT EXISTS idx_crm_login_history_profile_id_fkey ON public.crm_login_history (profile_id); -- crm_login_history_profile_id_fkey
CREATE INDEX IF NOT EXISTS idx_crm_recently_viewed_module_id_fkey ON public.crm_recently_viewed (module_id); -- crm_recently_viewed_module_id_fkey
CREATE INDEX IF NOT EXISTS idx_crm_recently_viewed_organization_id_fkey ON public.crm_recently_viewed (organization_id); -- crm_recently_viewed_organization_id_fkey
CREATE INDEX IF NOT EXISTS idx_crm_recently_viewed_record_id_fkey ON public.crm_recently_viewed (record_id); -- crm_recently_viewed_record_id_fkey
CREATE INDEX IF NOT EXISTS idx_crm_records_advisor_id_fkey ON public.crm_records (advisor_id); -- crm_records_advisor_id_fkey
CREATE INDEX IF NOT EXISTS idx_crm_records_normalized_advisor_name_fkey ON public.crm_records (normalized_advisor_name); -- crm_records_canonical_advisor_id_fkey
CREATE INDEX IF NOT EXISTS idx_crm_records_market_type_fkey ON public.crm_records (market_type); -- crm_records_carrier_id_fkey
CREATE INDEX IF NOT EXISTS idx_crm_records_module_id_fkey ON public.crm_records (module_id); -- crm_records_module_id_fkey
CREATE INDEX IF NOT EXISTS idx_crm_report_results_cache_report_id_fkey ON public.crm_report_results_cache (report_id); -- crm_report_results_cache_report_id_fkey
CREATE INDEX IF NOT EXISTS idx_crm_segmentations_created_by_fkey ON public.crm_segmentations (created_by); -- crm_segmentations_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_crm_segmentations_module_id_fkey ON public.crm_segmentations (module_id); -- crm_segmentations_module_id_fkey
CREATE INDEX IF NOT EXISTS idx_crm_sso_config_created_by_fkey ON public.crm_sso_config (created_by); -- crm_sso_config_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_crm_system_settings_updated_by_fkey ON public.crm_system_settings (updated_by); -- crm_system_settings_updated_by_fkey
CREATE INDEX IF NOT EXISTS idx_crm_tags_created_by_fkey ON public.crm_tags (created_by); -- crm_tags_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_crm_trusted_domains_added_by_fkey ON public.crm_trusted_domains (added_by); -- crm_trusted_domains_added_by_fkey
CREATE INDEX IF NOT EXISTS idx_crm_user_preferences_org_id_fkey ON public.crm_user_preferences (org_id); -- crm_user_preferences_org_id_fkey
CREATE INDEX IF NOT EXISTS idx_crm_user_roles_granted_by_fkey ON public.crm_user_roles (granted_by); -- crm_user_roles_granted_by_fkey
CREATE INDEX IF NOT EXISTS idx_crm_webhooks_created_by_fkey ON public.crm_webhooks (created_by); -- crm_webhooks_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_deal_blockers_created_by_fkey ON public.deal_blockers (created_by); -- deal_blockers_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_deal_blockers_org_id_fkey ON public.deal_blockers (org_id); -- deal_blockers_org_id_fkey
CREATE INDEX IF NOT EXISTS idx_deal_blockers_owner_id_fkey ON public.deal_blockers (owner_id); -- deal_blockers_owner_id_fkey
CREATE INDEX IF NOT EXISTS idx_deal_blockers_resolved_by_fkey ON public.deal_blockers (resolved_by); -- deal_blockers_resolved_by_fkey
CREATE INDEX IF NOT EXISTS idx_deal_war_room_notes_created_by_fkey ON public.deal_war_room_notes (created_by); -- deal_war_room_notes_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_deal_war_room_notes_org_id_fkey ON public.deal_war_room_notes (org_id); -- deal_war_room_notes_org_id_fkey
CREATE INDEX IF NOT EXISTS idx_dependent_coverage_periods_created_by_fkey ON public.dependent_coverage_periods (created_by); -- dependent_coverage_periods_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_doc_folders_created_by_fkey ON public.doc_folders (created_by); -- doc_folders_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_doc_folders_parent_id_fkey ON public.doc_folders (parent_id); -- doc_folders_parent_id_fkey
CREATE INDEX IF NOT EXISTS idx_document_audit_log_user_id_fkey ON public.document_audit_log (user_id); -- document_audit_log_user_id_fkey
CREATE INDEX IF NOT EXISTS idx_document_favorites_document_id_fkey ON public.document_favorites (document_id); -- document_favorites_document_id_fkey
CREATE INDEX IF NOT EXISTS idx_document_favorites_folder_id_fkey ON public.document_favorites (folder_id); -- document_favorites_folder_id_fkey
CREATE INDEX IF NOT EXISTS idx_document_favorites_org_id_fkey ON public.document_favorites (org_id); -- document_favorites_org_id_fkey
CREATE INDEX IF NOT EXISTS idx_document_links_created_by_fkey ON public.document_links (created_by); -- document_links_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_document_links_document_id_fkey ON public.document_links (document_id); -- document_links_document_id_fkey
CREATE INDEX IF NOT EXISTS idx_document_links_org_id_fkey ON public.document_links (org_id); -- document_links_org_id_fkey
CREATE INDEX IF NOT EXISTS idx_document_templates_created_by_fkey ON public.document_templates (created_by); -- document_templates_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_document_versions_uploaded_by_fkey ON public.document_versions (uploaded_by); -- document_versions_uploaded_by_fkey
CREATE INDEX IF NOT EXISTS idx_documents_folder_id_fkey ON public.documents (folder_id); -- documents_folder_id_fkey
CREATE INDEX IF NOT EXISTS idx_documents_uploaded_by_fkey ON public.documents (uploaded_by); -- documents_uploaded_by_fkey
CREATE INDEX IF NOT EXISTS idx_email_sequence_enrollments_current_step_id_fkey ON public.email_sequence_enrollments (current_step_id); -- email_sequence_enrollments_current_step_id_fkey
CREATE INDEX IF NOT EXISTS idx_email_sequence_enrollments_enrolled_by_fkey ON public.email_sequence_enrollments (enrolled_by); -- email_sequence_enrollments_enrolled_by_fkey
CREATE INDEX IF NOT EXISTS idx_email_sequence_steps_template_id_fkey ON public.email_sequence_steps (template_id); -- email_sequence_steps_template_id_fkey
CREATE INDEX IF NOT EXISTS idx_email_sequences_created_by_fkey ON public.email_sequences (created_by); -- email_sequences_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_enrollment_dependents_inactive_reason_fkey ON public.enrollment_dependents (inactive_reason); -- enrollment_dependents_inactive_reason_fkey
CREATE INDEX IF NOT EXISTS idx_enrollment_dependents_organization_id_fkey ON public.enrollment_dependents (organization_id); -- enrollment_dependents_organization_id_fkey
CREATE INDEX IF NOT EXISTS idx_enrollment_link_analytics_advisor_id_fkey ON public.enrollment_link_analytics (advisor_id); -- enrollment_link_analytics_advisor_id_fkey
CREATE INDEX IF NOT EXISTS idx_enrollment_link_conversions_advisor_id_fkey ON public.enrollment_link_conversions (advisor_id); -- enrollment_link_conversions_advisor_id_fkey
CREATE INDEX IF NOT EXISTS idx_enrollment_link_conversions_member_id_fkey ON public.enrollment_link_conversions (member_id); -- enrollment_link_conversions_member_id_fkey
CREATE INDEX IF NOT EXISTS idx_enrollment_link_visits_advisor_id_fkey ON public.enrollment_link_visits (advisor_id); -- enrollment_link_visits_advisor_id_fkey
CREATE INDEX IF NOT EXISTS idx_enrollment_links_product_id_fkey ON public.enrollment_links (product_id); -- enrollment_links_product_id_fkey
CREATE INDEX IF NOT EXISTS idx_enrollment_logs_advisor_id_fkey ON public.enrollment_logs (advisor_id); -- enrollment_logs_advisor_id_fkey
CREATE INDEX IF NOT EXISTS idx_enrollment_logs_profile_id_fkey ON public.enrollment_logs (profile_id); -- enrollment_logs_profile_id_fkey
CREATE INDEX IF NOT EXISTS idx_enrollment_wizard_state_enrollment_id_fkey ON public.enrollment_wizard_state (enrollment_id); -- enrollment_wizard_state_enrollment_id_fkey
CREATE INDEX IF NOT EXISTS idx_enrollment_wizard_state_member_id_fkey ON public.enrollment_wizard_state (member_id); -- enrollment_wizard_state_member_id_fkey
CREATE INDEX IF NOT EXISTS idx_enrollment_wizard_state_organization_id_fkey ON public.enrollment_wizard_state (organization_id); -- enrollment_wizard_state_organization_id_fkey
CREATE INDEX IF NOT EXISTS idx_enrollments_inactive_reason_fkey ON public.enrollments (inactive_reason); -- enrollments_inactive_reason_fkey
CREATE INDEX IF NOT EXISTS idx_enrollments_last_modified_by_fkey ON public.enrollments (last_modified_by); -- enrollments_last_modified_by_fkey
CREATE INDEX IF NOT EXISTS idx_esign_envelopes_connection_id_fkey ON public.esign_envelopes (connection_id); -- esign_envelopes_connection_id_fkey
CREATE INDEX IF NOT EXISTS idx_financial_audit_log_organization_id_fkey ON public.financial_audit_log (organization_id); -- financial_audit_log_organization_id_fkey
CREATE INDEX IF NOT EXISTS idx_forecasts_created_by_fkey ON public.forecasts (created_by); -- forecasts_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_forecasts_previous_forecast_id_fkey ON public.forecasts (previous_forecast_id); -- forecasts_previous_forecast_id_fkey
CREATE INDEX IF NOT EXISTS idx_franchise_revenue_shares_created_by_fkey ON public.franchise_revenue_shares (created_by); -- franchise_revenue_shares_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_import_mapping_templates_created_by_fkey ON public.import_mapping_templates (created_by); -- import_mapping_templates_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_inbox_conversations_assigned_to_fkey ON public.inbox_conversations (assigned_to); -- inbox_conversations_assigned_to_fkey
CREATE INDEX IF NOT EXISTS idx_inbox_drafts_org_id_fkey ON public.inbox_drafts (org_id); -- inbox_drafts_org_id_fkey
CREATE INDEX IF NOT EXISTS idx_inbox_drafts_signature_id_fkey ON public.inbox_drafts (signature_id); -- inbox_drafts_signature_id_fkey
CREATE INDEX IF NOT EXISTS idx_integration_jobs_source_event_id_fkey ON public.integration_jobs (source_event_id); -- integration_jobs_source_event_id_fkey
CREATE INDEX IF NOT EXISTS idx_integration_webhooks_connection_id_fkey ON public.integration_webhooks (connection_id); -- integration_webhooks_connection_id_fkey
CREATE INDEX IF NOT EXISTS idx_invoice_generation_jobs_created_by_fkey ON public.invoice_generation_jobs (created_by); -- invoice_generation_jobs_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_invoice_group_members_added_by_fkey ON public.invoice_group_members (added_by); -- invoice_group_members_added_by_fkey
CREATE INDEX IF NOT EXISTS idx_invoice_groups_created_by_fkey ON public.invoice_groups (created_by); -- invoice_groups_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_invoice_groups_last_generated_by_fkey ON public.invoice_groups (last_generated_by); -- invoice_groups_last_generated_by_fkey
CREATE INDEX IF NOT EXISTS idx_invoices_generation_job_id_fkey ON public.invoices (generation_job_id); -- invoices_generation_job_id_fkey
CREATE INDEX IF NOT EXISTS idx_invoices_original_invoice_id_fkey ON public.invoices (original_invoice_id); -- invoices_original_invoice_id_fkey
CREATE INDEX IF NOT EXISTS idx_job_definitions_created_by_fkey ON public.job_definitions (created_by); -- job_definitions_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_job_runs_retried_from_id_fkey ON public.job_runs (retried_from_id); -- job_runs_retried_from_id_fkey
CREATE INDEX IF NOT EXISTS idx_job_runs_triggered_by_fkey ON public.job_runs (triggered_by); -- job_runs_triggered_by_fkey
CREATE INDEX IF NOT EXISTS idx_legal_documents_created_by_fkey ON public.legal_documents (created_by); -- legal_documents_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_legal_documents_product_id_fkey ON public.legal_documents (product_id); -- legal_documents_product_id_fkey
CREATE INDEX IF NOT EXISTS idx_member_change_requests_decided_by_fkey ON public.member_change_requests (decided_by); -- member_change_requests_decided_by_fkey
CREATE INDEX IF NOT EXISTS idx_member_documents_issued_by_fkey ON public.member_documents (issued_by); -- member_documents_issued_by_fkey
CREATE INDEX IF NOT EXISTS idx_member_lifecycle_events_created_by_fkey ON public.member_lifecycle_events (created_by); -- member_lifecycle_events_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_nacha_files_created_by_fkey ON public.nacha_files (created_by); -- nacha_files_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_need_attachments_uploaded_by_fkey ON public.need_attachments (uploaded_by); -- need_attachments_uploaded_by_fkey
CREATE INDEX IF NOT EXISTS idx_notification_queue_advisor_id_fkey ON public.notification_queue (advisor_id); -- notification_queue_advisor_id_fkey
CREATE INDEX IF NOT EXISTS idx_notification_queue_member_id_fkey ON public.notification_queue (member_id); -- notification_queue_member_id_fkey
CREATE INDEX IF NOT EXISTS idx_notification_queue_profile_id_fkey ON public.notification_queue (profile_id); -- notification_queue_profile_id_fkey
CREATE INDEX IF NOT EXISTS idx_notification_queue_sent_email_id_fkey ON public.notification_queue (sent_email_id); -- notification_queue_sent_email_id_fkey
CREATE INDEX IF NOT EXISTS idx_notification_queue_template_id_fkey ON public.notification_queue (template_id); -- notification_queue_template_id_fkey
CREATE INDEX IF NOT EXISTS idx_ops_audit_log_actor_id_fkey ON public.ops_audit_log (actor_id); -- ops_audit_log_actor_id_fkey
CREATE INDEX IF NOT EXISTS idx_org_delegations_granted_by_fkey ON public.org_delegations (granted_by); -- org_delegations_granted_by_fkey
CREATE INDEX IF NOT EXISTS idx_organization_members_invited_by_fkey ON public.organization_members (invited_by); -- organization_members_invited_by_fkey
CREATE INDEX IF NOT EXISTS idx_organizations_owner_user_id_fkey ON public.organizations (owner_user_id); -- organizations_owner_user_id_fkey
CREATE INDEX IF NOT EXISTS idx_payable_categories_organization_id_fkey ON public.payable_categories (organization_id); -- payable_categories_organization_id_fkey
CREATE INDEX IF NOT EXISTS idx_payable_line_items_payable_id_fkey ON public.payable_line_items (payable_id); -- payable_line_items_payable_id_fkey
CREATE INDEX IF NOT EXISTS idx_payable_payments_created_by_fkey ON public.payable_payments (created_by); -- payable_payments_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_payable_payments_payable_id_fkey ON public.payable_payments (payable_id); -- payable_payments_payable_id_fkey
CREATE INDEX IF NOT EXISTS idx_payables_approved_by_fkey ON public.payables (approved_by); -- payables_approved_by_fkey
CREATE INDEX IF NOT EXISTS idx_payables_category_id_fkey ON public.payables (category_id); -- payables_category_id_fkey
CREATE INDEX IF NOT EXISTS idx_payables_created_by_fkey ON public.payables (created_by); -- payables_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_payment_processors_created_by_fkey ON public.payment_processors (created_by); -- payment_processors_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_payment_transactions_payment_profile_id_fkey ON public.payment_transactions (payment_profile_id); -- payment_transactions_payment_profile_id_fkey
CREATE INDEX IF NOT EXISTS idx_payment_webhooks_organization_id_fkey ON public.payment_webhooks (organization_id); -- payment_webhooks_organization_id_fkey
CREATE INDEX IF NOT EXISTS idx_payout_approvals_approver_id_fkey ON public.payout_approvals (approver_id); -- payout_approvals_approver_id_fkey
CREATE INDEX IF NOT EXISTS idx_payout_batch_logs_actor_id_fkey ON public.payout_batch_logs (actor_id); -- payout_batch_logs_actor_id_fkey
CREATE INDEX IF NOT EXISTS idx_payout_exports_exported_by_fkey ON public.payout_exports (exported_by); -- payout_exports_exported_by_fkey
CREATE INDEX IF NOT EXISTS idx_payout_fraud_flags_batch_id_fkey ON public.payout_fraud_flags (batch_id); -- payout_fraud_flags_batch_id_fkey
CREATE INDEX IF NOT EXISTS idx_payout_fraud_flags_resolved_by_fkey ON public.payout_fraud_flags (resolved_by); -- payout_fraud_flags_resolved_by_fkey
CREATE INDEX IF NOT EXISTS idx_payout_provider_transactions_provider_id_fkey ON public.payout_provider_transactions (provider_id); -- payout_provider_transactions_provider_id_fkey
CREATE INDEX IF NOT EXISTS idx_payout_reconciliation_logs_payout_item_id_fkey ON public.payout_reconciliation_logs (payout_item_id); -- payout_reconciliation_logs_payout_item_id_fkey
CREATE INDEX IF NOT EXISTS idx_payout_reconciliation_logs_provider_txn_id_fkey ON public.payout_reconciliation_logs (provider_txn_id); -- payout_reconciliation_logs_provider_txn_id_fkey
CREATE INDEX IF NOT EXISTS idx_payout_reconciliation_logs_resolved_by_fkey ON public.payout_reconciliation_logs (resolved_by); -- payout_reconciliation_logs_resolved_by_fkey
CREATE INDEX IF NOT EXISTS idx_plan_rates_age_band_id_fkey ON public.plan_rates (age_band_id); -- plan_rates_age_band_id_fkey
CREATE INDEX IF NOT EXISTS idx_plan_rates_rating_area_id_fkey ON public.plan_rates (rating_area_id); -- plan_rates_rating_area_id_fkey
CREATE INDEX IF NOT EXISTS idx_plan_versions_approved_by_fkey ON public.plan_versions (approved_by); -- plan_versions_approved_by_fkey
CREATE INDEX IF NOT EXISTS idx_plan_versions_created_by_fkey ON public.plan_versions (created_by); -- plan_versions_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_playbook_checklists_org_id_fkey ON public.playbook_checklists (org_id); -- playbook_checklists_org_id_fkey
CREATE INDEX IF NOT EXISTS idx_playbook_progress_org_id_fkey ON public.playbook_progress (org_id); -- playbook_progress_org_id_fkey
CREATE INDEX IF NOT EXISTS idx_playbook_progress_playbook_id_fkey ON public.playbook_progress (playbook_id); -- playbook_progress_playbook_id_fkey
CREATE INDEX IF NOT EXISTS idx_premium_comparisons_created_by_fkey ON public.premium_comparisons (created_by); -- premium_comparisons_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_price_change_audit_billing_schedule_id_fkey ON public.price_change_audit (billing_schedule_id); -- price_change_audit_billing_schedule_id_fkey
CREATE INDEX IF NOT EXISTS idx_price_change_schedules_created_by_fkey ON public.price_change_schedules (created_by); -- price_change_schedules_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_price_change_schedules_executed_by_fkey ON public.price_change_schedules (executed_by); -- price_change_schedules_executed_by_fkey
CREATE INDEX IF NOT EXISTS idx_price_change_schedules_plan_id_fkey ON public.price_change_schedules (plan_id); -- price_change_schedules_plan_id_fkey
CREATE INDEX IF NOT EXISTS idx_product_audit_log_user_id_fkey ON public.product_audit_log (user_id); -- product_audit_log_user_id_fkey
CREATE INDEX IF NOT EXISTS idx_product_benefits_product_id_fkey ON public.product_benefits (product_id); -- product_benefits_product_id_fkey
CREATE INDEX IF NOT EXISTS idx_product_documents_organization_id_fkey ON public.product_documents (organization_id); -- product_documents_organization_id_fkey
CREATE INDEX IF NOT EXISTS idx_product_extra_costs_product_id_fkey ON public.product_extra_costs (product_id); -- product_extra_costs_product_id_fkey
CREATE INDEX IF NOT EXISTS idx_product_pricing_matrix_age_bracket_id_fkey ON public.product_pricing_matrix (age_bracket_id); -- product_pricing_matrix_age_bracket_id_fkey
CREATE INDEX IF NOT EXISTS idx_promo_codes_created_by_fkey ON public.promo_codes (created_by); -- promo_codes_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_quote_snapshots_benefit_tier_id_fkey ON public.quote_snapshots (benefit_tier_id); -- quote_snapshots_benefit_tier_id_fkey
CREATE INDEX IF NOT EXISTS idx_scheduled_appointments_contact_id_fkey ON public.scheduled_appointments (contact_id); -- scheduled_appointments_contact_id_fkey
CREATE INDEX IF NOT EXISTS idx_scheduled_appointments_lead_id_fkey ON public.scheduled_appointments (lead_id); -- scheduled_appointments_lead_id_fkey
CREATE INDEX IF NOT EXISTS idx_scheduling_bookings_host_id_fkey ON public.scheduling_bookings (host_id); -- scheduling_bookings_host_id_fkey
CREATE INDEX IF NOT EXISTS idx_sent_emails_advisor_id_fkey ON public.sent_emails (advisor_id); -- sent_emails_advisor_id_fkey
CREATE INDEX IF NOT EXISTS idx_sent_emails_enrollment_id_fkey ON public.sent_emails (enrollment_id); -- sent_emails_enrollment_id_fkey
CREATE INDEX IF NOT EXISTS idx_sent_emails_member_id_fkey ON public.sent_emails (member_id); -- sent_emails_member_id_fkey
CREATE INDEX IF NOT EXISTS idx_sent_emails_template_id_fkey ON public.sent_emails (template_id); -- sent_emails_template_id_fkey
CREATE INDEX IF NOT EXISTS idx_slack_messages_log_connection_id_fkey ON public.slack_messages_log (connection_id); -- slack_messages_log_connection_id_fkey
CREATE INDEX IF NOT EXISTS idx_slack_subscriptions_connection_id_fkey ON public.slack_subscriptions (connection_id); -- slack_subscriptions_connection_id_fkey
CREATE INDEX IF NOT EXISTS idx_system_settings_last_changed_by_fkey ON public.system_settings (last_changed_by); -- system_settings_last_changed_by_fkey
CREATE INDEX IF NOT EXISTS idx_team_invitations_accepted_by_fkey ON public.team_invitations (accepted_by); -- team_invitations_accepted_by_fkey
CREATE INDEX IF NOT EXISTS idx_team_invitations_invited_by_fkey ON public.team_invitations (invited_by); -- team_invitations_invited_by_fkey
CREATE INDEX IF NOT EXISTS idx_tenant_audit_log_actor_user_id_fkey ON public.tenant_audit_log (actor_user_id); -- tenant_audit_log_actor_user_id_fkey
CREATE INDEX IF NOT EXISTS idx_vendor_changes_file_row_id_fkey ON public.vendor_changes (file_row_id); -- vendor_changes_file_row_id_fkey
CREATE INDEX IF NOT EXISTS idx_vendor_changes_reviewed_by_fkey ON public.vendor_changes (reviewed_by); -- vendor_changes_reviewed_by_fkey
CREATE INDEX IF NOT EXISTS idx_vendor_connectors_created_by_fkey ON public.vendor_connectors (created_by); -- vendor_connectors_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_vendor_connectors_updated_by_fkey ON public.vendor_connectors (updated_by); -- vendor_connectors_updated_by_fkey
CREATE INDEX IF NOT EXISTS idx_vendor_costs_organization_id_fkey ON public.vendor_costs (organization_id); -- vendor_costs_organization_id_fkey
CREATE INDEX IF NOT EXISTS idx_vendor_credentials_created_by_fkey ON public.vendor_credentials (created_by); -- vendor_credentials_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_vendor_eligibility_runs_job_run_id_fkey ON public.vendor_eligibility_runs (job_run_id); -- vendor_eligibility_runs_job_run_id_fkey
CREATE INDEX IF NOT EXISTS idx_vendor_eligibility_runs_retried_from_id_fkey ON public.vendor_eligibility_runs (retried_from_id); -- vendor_eligibility_runs_retried_from_id_fkey
CREATE INDEX IF NOT EXISTS idx_vendor_eligibility_runs_triggered_by_fkey ON public.vendor_eligibility_runs (triggered_by); -- vendor_eligibility_runs_triggered_by_fkey
CREATE INDEX IF NOT EXISTS idx_vendor_file_rows_org_id_fkey ON public.vendor_file_rows (org_id); -- vendor_file_rows_org_id_fkey
CREATE INDEX IF NOT EXISTS idx_vendor_files_uploaded_by_fkey ON public.vendor_files (uploaded_by); -- vendor_files_uploaded_by_fkey
CREATE INDEX IF NOT EXISTS idx_vendor_job_configs_created_by_fkey ON public.vendor_job_configs (created_by); -- vendor_job_configs_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_vendors_created_by_fkey ON public.vendors (created_by); -- vendors_created_by_fkey
CREATE INDEX IF NOT EXISTS idx_vendors_updated_by_fkey ON public.vendors (updated_by); -- vendors_updated_by_fkey
CREATE INDEX IF NOT EXISTS idx_warehouse_exports_requested_by_fkey ON public.warehouse_exports (requested_by); -- warehouse_exports_requested_by_fkey
CREATE INDEX IF NOT EXISTS idx_webhooks_created_by_fkey ON public.webhooks (created_by); -- webhooks_created_by_fkey

COMMIT;

NOTIFY pgrst, 'reload schema';
